### ISSUE TITLE
Ooops? NRE when opening new console project .NET Core in VS 2019 16.8 Preview 3.1

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#10231]
I'm gonna assume this is a glitch or was already reported and I missed it, but in VS 2019 16.8, Preview 3.1, when trying to add a new project through the menu, selecting .NET Core, Console, F#, I get an NRE messagebox:

![image](https://user-images.githubusercontent.com/16015770/95256290-e80cdf00-0822-11eb-8c94-074b4f1d94d2.png)

After clicking the messagebox away, VS crashes (then auto-restarts).

![image](https://user-images.githubusercontent.com/16015770/95256449-1ee2f500-0823-11eb-94e8-5a0f57fb372b.png)

After restart, same issue (i.e., it appears to be reproducible). 

Dumping this here in case this is a _known issue_. If not, I'll try to figure out what's going on. ~I'll update once I've investigated the logs.~ 

The log gives:

```
Exception occurred while executing the command to show the New Project Dialog. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.NewProjectDialog.NpdStateMachine.CanNavigateForward()
   at Microsoft.VisualStudio.NewProjectDialog.NewProjectDialogViewModel.CanGoNext(Object parameter)
   at Microsoft.VisualStudio.PlatformUI.DelegateCommand`1.CanExecute(Object parameter)
   at Microsoft.VisualStudio.PlatformUI.DispatchedDelegateCommand`1.CanExecute(Object parameter)
   at Microsoft.VisualStudio.PlatformUI.GetToCode.WorkflowHostViewModel.WorkflowDecorator.CanGoNext(Object obj)
   at Microsoft.VisualStudio.PlatformUI.DelegateCommand.CanExecute(Object parameter)
   at Microsoft.VisualStudio.PlatformUI.GetToCode.WorkflowHostViewModel.CanGoNext(Object obj)
   at Microsoft.VisualStudio.PlatformUI.DelegateCommand.CanExecute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CanExecuteCommandSource(ICommandSource commandSource)
   at System.Windows.Controls.Primitives.ButtonBase.UpdateCanExecute()
   at System.Windows.Controls.Primitives.ButtonBase.OnCanExecuteChanged(Object sender, EventArgs e)
   at System.Windows.Input.CanExecuteChangedEventManager.HandlerSink.OnCanExecuteChanged(Object sender, EventArgs e)
   at Microsoft.VisualStudio.PlatformUI.DelegateCommandBase.RaiseCanExecuteChanged()
   at Microsoft.VisualStudio.PlatformUI.GetToCode.WorkflowHostViewModel.<.ctor>b__13_0(Object s, EventArgs e)
   at Microsoft.VisualStudio.PlatformUI.DelegateCommandBase.RaiseCanExecuteChanged()
   at Microsoft.VisualStudio.PlatformUI.GetToCode.WorkflowHostViewModel.WorkflowDecorator.<AddHandlers>b__34_0(Object s, EventArgs e)
   at Microsoft.VisualStudio.PlatformUI.DelegateCommandBase.RaiseCanExecuteChanged()
   at Microsoft.VisualStudio.PlatformUI.DispatchedDelegateCommand`1.<>c__DisplayClass8_0.<Execute>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at Microsoft.Internal.VisualStudio.PlatformUI.WindowHelper.ShowModal(Window window, IntPtr parent)
   at Microsoft.VisualStudio.PlatformUI.GetToCode.WorkflowDialogService.ShowNewProjectDialog(VSNEWPROJECTDLGINFO dialogInfo)
   at Microsoft.VisualStudio.Dialogs.SVsDialogService.TryInvokeWorkflowDialog(VSNEWPROJECTDLGINFO dlgInfo, Int32& result) --- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by abelbraaksma** [comment]
Restarts didn't help. What did help, was opening an older solution, adding a project there. After that, VS with the new solution didn't start at all (crashed without messagebox) at first, but then suddenly worked again.

Will monitor if it happens again. 

Afaik I wasn't doing something out of the ordinary (I often do, I know, but not today ;).

**Comment by cartermp** [comment]
This appears to be an installer bug or some kind of environmental issue that affects the installer as per the screenshot. If you could file a VSFeedback ticket with the stack trace attached (and emphasize _Installer_ so that the system doesn't mistriage it to F# simply because you were using F#) then the right folks can look at it.

**Comment by abelbraaksma** [comment]
@cartermp, sure, I can do that, but how is this an installer bug? I've installed this version a few weeks ago and this happened after several hours working in VS.

**Comment by cartermp** [comment]
Sorry, I meant New Project Dialog.
