### ISSUE TITLE
Cannot use new package reference style for System.Xml.Linq

### ISSUE THREAD

**Issue by siavash-babaei** [dotnet/fsharp#10501]
Using #r "nuget: System.Xml.Linq" does not allow for open System.Xml.Linq resulting in a namespace not defined error. Using a local version  #r "./packages/nuget: System.Xml.Linq.dll" works just fine.

**Comment by baronfel** [comment]
You shouldn't _need_ to `#r "nuget"` that package, it's available in the base set of references included in `dotnet fsi`. Here's me doing something nonsensical on `dotnet fsi` for .net sdk 5.0:

```
> dotnet fsi
Microsoft (R) F# Interactive version 11.0.0.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> open System.Xml.Linq;;
> XDocument.Load "foo";;
System.IO.FileNotFoundException: Could not find file '/Users/chethusk/oss/FsAutoComplete/foo'.
File name: '/Users/chethusk/oss/FsAutoComplete/foo'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri)
   at <StartupCode$FSI_0003>.$FSI_0003.main@()
Stopped due to error
```

**Comment by siavash-babaei** [comment]
Dear @baronfel, what can I tell ya? The only case when it works is when I install the package and reference the local dll.

**Comment by baronfel** [comment]
Can you let us know what your execution environment is? Are you running `fsi.exe`, `fsiAnyCpu.exe`, `fsharpi`, a `dotnet fsi` from a particular version of a .Net Core SDK?

**Comment by siavash-babaei** [comment]
I am in Visual Studio 2019 16.8.1, .Net 5, F# 5.0, Windows 10 x64: Microsoft (R) F# Interactive version 11.0.0.0 for F# 5.0. What I am getting is IntelliSense errors and red wiggly lines in the script file.

**Comment by smoothdeveloper** [comment]
@siavash-babaei this works in both .NET framework FSI / VS and `dotnet fsi`:

```fsharp
#r "System.Xml.Linq"
open System.Xml.Linq
XDocument.Load "foo"
```

https://github.com/dotnet/fsharp/pull/10163 may be relevant issue for visual studio users.

**Comment by siavash-babaei** [comment]
Thank you @smoothdeveloper.
