### ISSUE TITLE
SetUp failed for test fixtures on Linux and Mac

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#10641]
Our current CI runs in "main" include the following output for Linux and Mac which looks like it may be supressing tests

@KevinRansom may be to do with recent changes in FX resolution?

```
2020-12-08T00:11:25.2140398Z SetUp failed for test fixture Tests.Service.ProjectAnalysisTests
2020-12-08T00:11:25.2147135Z An exception was thrown while loading the test.
2020-12-08T00:11:25.2148810Z System.ArgumentException: Unknown framework version 5.5 (Parameter 'version')
2020-12-08T00:11:25.2149598Z    at NUnit.Framework.Internal.RuntimeFramework.ThrowInvalidFrameworkVersion(Version version)
2020-12-08T00:11:25.2150332Z    at NUnit.Framework.Internal.RuntimeFramework.InitFromFrameworkVersion(Version version)
2020-12-08T00:11:25.2151045Z    at NUnit.Framework.Internal.RuntimeFramework..ctor(RuntimeType runtime, Version version)
2020-12-08T00:11:25.2151696Z    at NUnit.Framework.Internal.RuntimeFramework.<>c.<.cctor>b__33_0()
2020-12-08T00:11:25.2152307Z    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2020-12-08T00:11:25.2153117Z --- End of stack trace from previous location ---
2020-12-08T00:11:25.2153910Z    at System.Lazy`1.CreateValue()
2020-12-08T00:11:25.2154420Z    at System.Lazy`1.get_Value()
2020-12-08T00:11:25.2154967Z    at NUnit.Framework.Internal.RuntimeFramework.get_CurrentFramework()
2020-12-08T00:11:25.2155575Z    at NUnit.Framework.Internal.PlatformHelper..ctor()
2020-12-08T00:11:25.2156210Z    at NUnit.Framework.TestCaseAttribute.BuildFrom(IMethodInfo method, Test suite)+MoveNext()
2020-12-08T00:11:25.2156959Z    at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite)
2020-12-08T00:11:25.2157759Z    at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture, IPreFilter filter)
2020-12-08T00:11:25.2158545Z    at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)
2020-12-08T00:11:25.2159309Z    at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)
2020-12-08T00:11:25.2169388Z SetUp failed for test fixture Tests.Service.ScriptOptions
2020-12-08T00:11:25.2174529Z An exception was thrown while loading the test.
2020-12-08T00:11:25.2175978Z System.ArgumentException: Unknown framework version 5.5 (Parameter 'version')
2020-12-08T00:11:25.2176748Z    at NUnit.Framework.Internal.RuntimeFramework.ThrowInvalidFrameworkVersion(Version version)
2020-12-08T00:11:25.2177509Z    at NUnit.Framework.Internal.RuntimeFramework.InitFromFrameworkVersion(Version version)
2020-12-08T00:11:25.2178450Z    at NUnit.Framework.Internal.RuntimeFramework..ctor(RuntimeType runtime, Version version)
2020-12-08T00:11:25.2179126Z    at NUnit.Framework.Internal.RuntimeFramework.<>c.<.cctor>b__33_0()
2020-12-08T00:11:25.2180008Z    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2020-12-08T00:11:25.2180695Z    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2020-12-08T00:11:25.2181341Z    at System.Lazy`1.CreateValue()
2020-12-08T00:11:25.2181828Z    at System.Lazy`1.get_Value()
2020-12-08T00:11:25.2182389Z    at NUnit.Framework.Internal.RuntimeFramework.get_CurrentFramework()
2020-12-08T00:11:25.2182997Z    at NUnit.Framework.Internal.PlatformHelper..ctor()
2020-12-08T00:11:25.2183618Z    at NUnit.Framework.TestCaseAttribute.BuildFrom(IMethodInfo method, Test suite)+MoveNext()
2020-12-08T00:11:25.2184358Z    at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite)
2020-12-08T00:11:25.2185156Z    at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture, IPreFilter filter)
2020-12-08T00:11:25.2185975Z    at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)
2020-12-08T00:11:25.2186742Z    at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)
2020-12-08T00:11:26.7152152Z   Skipped Type provider project references should not throw exceptions [< 1 ms]
2020-12-08T00:11:37.6446194Z SetUp failed for test fixture Tests.Service.ServiceUntypedParseTests+AttributeCompletion
2020-12-08T00:11:37.6453300Z An exception was thrown while loading the test.
2020-12-08T00:11:37.6454665Z System.ArgumentException: Unknown framework version 5.5 (Parameter 'version')
2020-12-08T00:11:37.6455431Z    at NUnit.Framework.Internal.RuntimeFramework.ThrowInvalidFrameworkVersion(Version version)
2020-12-08T00:11:37.6456343Z    at NUnit.Framework.Internal.RuntimeFramework.InitFromFrameworkVersion(Version version)
2020-12-08T00:11:37.6457185Z    at NUnit.Framework.Internal.RuntimeFramework..ctor(RuntimeType runtime, Version version)
2020-12-08T00:11:37.6457884Z    at NUnit.Framework.Internal.RuntimeFramework.<>c.<.cctor>b__33_0()
2020-12-08T00:11:37.6458485Z    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2020-12-08T00:11:37.6459559Z --- End of stack trace from previous location ---
2020-12-08T00:11:37.6460153Z    at System.Lazy`1.CreateValue()
2020-12-08T00:11:37.6460860Z    at System.Lazy`1.get_Value()
2020-12-08T00:11:37.6461410Z    at NUnit.Framework.Internal.RuntimeFramework.get_CurrentFramework()
2020-12-08T00:11:37.6462017Z    at NUnit.Framework.Internal.PlatformHelper..ctor()
2020-12-08T00:11:37.6462657Z    at NUnit.Framework.TestCaseAttribute.BuildFrom(IMethodInfo method, Test suite)+MoveNext()
2020-12-08T00:11:37.6463391Z    at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite)
2020-12-08T00:11:37.6464217Z    at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture, IPreFilter filter)
2020-12-08T00:11:37.6465099Z    at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)
2020-12-08T00:11:37.6465871Z    at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)
2020-12-08T00:12:58.8686311Z Results File: /home/vsts/work/1/s/artifacts/TestResults/Release/FSharp.Compiler.Service.Tests_netcoreapp3.1.xml
2020-12-08T00:12:58.8688986Z 
```

**Comment by KevinRansom** [comment]
This no longer repros for me.  Please reopen if you still see it.

Kevin
