### ISSUE TITLE
Resolving ONNX runtime fails

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#10856]
Over in the notebook repo is this issue:   https://github.com/dotnet/interactive/issues/967

The following code

```csharp
#r "nuget:Microsoft.ML.OnnxRuntime.Managed,1.5.2"
#r "nuget:Microsoft.ML.OnnxRuntime,1.5.2"

using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;

var session = new InferenceSession("path to a valid onnx model", new SessionOptions
    {
        LogSeverityLevel = OrtLoggingLevel.ORT_LOGGING_LEVEL_ERROR
    });
```

Produces the following errors

```
Error: System.TypeInitializationException: The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.
---> System.EntryPointNotFoundException: Unable to find an entry point named 'OrtGetApiBase' in DLL 'onnxruntime'.
at Microsoft.ML.OnnxRuntime.NativeMethods.OrtGetApiBase()
at Microsoft.ML.OnnxRuntime.NativeMethods..cctor() in C:\a\1\s\csharp\src\Microsoft.ML.OnnxRuntime\NativeMethods.cs:line 193
--- End of inner exception stack trace ---
at Microsoft.ML.OnnxRuntime.SessionOptions..ctor() in C:\a\1\s\csharp\src\Microsoft.ML.OnnxRuntime\SessionOptions.cs:line 50
at Submission#5.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

**Comment by KevinRansom** [comment]
Fixed by: https://github.com/dotnet/fsharp/pull/10857

**Comment by cartermp** [comment]
This was never fixed in the linked PR, since that PR was simply closed.

**Comment by KevinRansom** [comment]
Bugger

**Comment by KevinRansom** [comment]
Per: https://github.com/dotnet/interactive/issues/967

@colombod ,

I believe this is fixed.  When I run the repo, I now see a dfferent error and that error looks to be the one I would expect to see, model file doesn't exist.

Can we close this?
````
Microsoft (R) F# Interactive version 12.5.0.0 for F# 7.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> #r "nuget:Microsoft.ML.OnnxRuntime.Managed,1.5.2"
- #r "nuget:Microsoft.ML.OnnxRuntime,1.5.2"
-
- open Microsoft.ML.OnnxRuntime
- open Microsoft.ML.OnnxRuntime.Tensors
-
- let session = new InferenceSession("path to a valid onnx model", new SessionOptions(LogSeverityLevel = OrtLoggingLevel.ORT_LOGGING_LEVEL_ERROR));;
[Loading C:\Users\kevinr\.packagemanagement\nuget\Cache\951f9086aa245bd46c2a954539f5e1686dfbbf334bd24cb5709787e7931b4ecc.fsx]
module FSI_0002.
       951f9086aa245bd46c2a954539f5e1686dfbbf334bd24cb5709787e7931b4ecc

Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:NoSuchFile] Load model from path to a valid onnx model failed:Load model path to a valid onnx model failed. File doesn't exist
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus) in C:\a\1\s\csharp\src\Microsoft.ML.OnnxRuntime\NativeApiStatus.cs:line 32
   at Microsoft.ML.OnnxRuntime.InferenceSession.Init(String modelPath, SessionOptions options) in C:\a\1\s\csharp\src\Microsoft.ML.OnnxRuntime\InferenceSession.cs:line 667
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath, SessionOptions options) in C:\a\1\s\csharp\src\Microsoft.ML.OnnxRuntime\InferenceSession.cs:line 46
   at <StartupCode$FSI_0003>.$FSI_0003.main@() in c:\temp\stdin:line 7
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Stopped due to error
>
````
