### ISSUE TITLE
Tests fail in build.cmd

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#10968]
When running `./build.cmd -c Release -testDesktop` it fails with lots of errors like this:
```
  Passed FSharp.Core.UnitTests.Collections.SetModule.Fold [3 ms]
[xUnit.net 00:01:11.27]     FSharp.Core.UnitTests.Collections.CollectionModulesConsistency.findBack is consistent [FAIL]
[xUnit.net 00:01:11.27]       System.MissingMethodException : Method not found: 'Microsoft.FSharp.Core.FSharpOption`1<FsCheck.Replay> FsCheck.Config.get_Replay()'.
[xUnit.net 00:01:11.27]       Stack Trace:
[xUnit.net 00:01:11.27]            at FSharp.Core.UnitTests.Collections.CollectionModulesConsistency.smallerSizeCheck[a](a testable)
[xUnit.net 00:01:11.27]         FSharp.Core\Microsoft.FSharp.Collections\CollectionModulesConsistency.fs(281,0): at FSharp.Core.UnitTests.Collections.CollectionModulesConsistency.findBack is consistent()
[xUnit.net 00:01:11.27]     FSharp.Core.UnitTests.Collections.CollectionModulesConsistency.tryLast is consistent [FAIL]
[xUnit.net 00:01:11.27]       System.MissingMethodException : Method not found: 'Microsoft.FSharp.Core.FSharpOption`1<FsCheck.Replay> FsCheck.Config.get_Replay()'.
[xUnit.net 00:01:11.27]       Stack Trace:
[xUnit.net 00:01:11.27]            at FSharp.Core.UnitTests.Collections.CollectionModulesConsistency.smallerSizeCheck[a](a testable)
[xUnit.net 00:01:11.27]         FSharp.Core\Microsoft.FSharp.Collections\CollectionModulesConsistency.fs(1183,0): at FSharp.Core.UnitTests.Collections.CollectionModulesConsistency.tryLast is consistent()
```

Windows 10
Windows Terminal + PowerShell

Is there any additional info I could provide?

**Comment by vzarytovskii** [comment]
Some additional errors:
```log
[xUnit.net 00:00:01.50]       System.InvalidCastException : Unable to cast object of type 'Arrow@249-1[System.Int32,Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,System.Boolean]]]]' to type 'Testable`1[Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,System.Boolean]]]]]'.
[xUnit.net 00:00:01.50]       Stack Trace:
[xUnit.net 00:00:01.50]            at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
[xUnit.net 00:00:01.50]            at FsCheck.Runner.check[a](Config config, a p)
[xUnit.net 00:00:01.50]            at FsCheck.Check.One[Testable](Config config, Testable property)
[xUnit.net 00:00:01.50]     FSharp.Core.UnitTests.DiscriminatedUnionTypes.struct unions support [<CustomEquality>] [FAIL]
```

**Comment by cartermp** [comment]
Any on how to resolve this?

**Comment by vzarytovskii** [comment]
> Any on how to resolve this?

Not from my initial investigation, I wasn't able to repro it on any of my machines.

**Comment by KevinRansom** [comment]
@auduchinok , if this still happens for you can you zip the contents of the artifacts\Log directory and the artifacts\bin\FSharp.Core.UnitTests  for the configuration you are testing, I will take a look.

Thanks

Kevin

**Comment by auduchinok** [comment]
@KevinRansom Thanks! Yes, I'll try to send the logs soon. I've previously send them to @vzarytovskii, so it could probably be faster to ask him for now.

**Comment by vzarytovskii** [comment]
Oops, I've missed Kevin's comment somehow. @KevinRansom [here are binlogs and build log](https://1drv.ms/u/s!AiT31MwroM_3lbY0vRfPWCmqpXUSEg?e=Nf2NTm).

**Comment by auduchinok** [comment]
It doesn't reproduce on a clean Windows install anymore.
