### ISSUE TITLE
FSI fails when printing anonymous record literal with repeated property name

### ISSUE THREAD

**Issue by theprash** [dotnet/fsharp#11270]
While printing an anonymous record with the same property appearing more than once FSI throws an exception, even though this is valid in the language.

**Repro steps**

Run `{| A = 1; A = 2 |}` in FSI.

**Expected behavior**

Print `{| A = 1 |}`

**Actual behavior**

```
Exception raised during pretty printing.
Please report this so it can be fixed.
Trace: System.InvalidOperationException: Multiple CompilationMappingAttributes, expected at most one
   at Microsoft.FSharp.Reflection.Impl.tryFindCompilationMappingAttribute(Object[] attrs) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\reflect.fs:line 168
   at Microsoft.FSharp.Reflection.Impl.isFieldProperty(PropertyInfo prop) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\reflect.fs:line 228
   at Microsoft.FSharp.Collections.ArrayModule.Filter.createMask[a](FSharpFunc`2 f, a[] src, UInt32[]& maskArrayOut, UInt32& leftoverMaskOut) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\array.fs:line 583
   at Microsoft.FSharp.Collections.ArrayModule.Filter.filter[a](FSharpFunc`2 f, a[] src) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\array.fs:line 670
   at Microsoft.FSharp.Reflection.Impl.fieldPropsOfRecordType(Type typ, BindingFlags bindingFlags)
   at Internal.Utilities.StructuredFormat.ReflectUtils.Value.GetValueInfoOfObject$cont@433(BindingFlags bindingFlags, Object obj, Type reprty, Unit unitVar) in F:\workspace\_work\1\s\src\utils\sformat.fs:line 446
   at Internal.Utilities.StructuredFormat.Display.ObjectGraphFormatter.objL(ShowMode showMode, Int32 depthLim, Precedence prec, Object x, Type ty) in F:\workspace\_work\1\s\src\utils\sformat.fs:line 834
   at Internal.Utilities.StructuredFormat.Display.Format@1216-4.Invoke(Int32 depthLim, Precedence prec, Tuple`2 tupledArg) in F:\workspace\_work\1\s\src\utils\sformat.fs:line 1216
   at FSharp.Compiler.Interactive.Shell.FsiValuePrinter.PrintValue(FsiValuePrinterMode printMode, FormatOptions opts, Object x, Type ty) in F:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 410
```

**Related information**

* Windows
* Tested on `dotnet fsi` (5.0.103) and VS 16.8.6

**Comment by dsyme** [comment]
I checked - this no longer fails
