### ISSUE TITLE
dotnet 5.0.5 coredump on ubuntu 21.04

### ISSUE THREAD

**Issue by netroby** [dotnet/fsharp#11387]
The core dump looks like

```
Core was generated by `/snap/dotnet-sdk/120/dotnet fsi'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa857486c78 in ?? ()
[Current thread is 1 (LWP 35415)]
(gdb) bt
#0  0x00007fa857486c78 in ?? ()
#1  0x00007fa855dc0af0 in ?? ()
#2  0x00007fa855dc0ac8 in ?? ()
#3  0x00007fa855dc0ac0 in ?? ()
#4  0x0000000000000000 in ?? ()
(gdb) 

```

When i try to run dotnet fsi
it crashed and have a core file

my system was:

```
huzhifeng@ak47 ~ $ uname -a
Linux ak47 5.11.0-13-lowlatency #14-Ubuntu SMP PREEMPT Fri Mar 19 18:13:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
huzhifeng@ak47 ~ $ dotnet version
[1]    35539 segmentation fault (core dumped)  dotnet version
huzhifeng@ak47 ~ $ dotnet --version
5.0.202


```

**Comment by netroby** [comment]
I found a similar report, but have no idea where to report it? https://github.com/dotnet/sdk/issues/15114

**Comment by cartermp** [comment]
I think the SDK is a good place to start. This looks like it is related to installing .NET via Snap, and not anything within the F# tools itself.
