### ISSUE TITLE
Incorrect exception stacktrace in F# scripts

### ISSUE THREAD

**Issue by reneederer** [dotnet/fsharp#11453]
I have a F# script:
```
let fail () = [].[5]
let start() = fail()
let main() =
    try
        printfn $"{start()}"
    with
    | e ->
        printfn $"{e}"
main()
```

```dotnet fsi script.fsx``` gives the unexpected output:
```
System.ArgumentException: The index was outside the range of elements in the list. (Parameter 'n')
   at Microsoft.FSharp.Collections.PrivateListHelpers.nth[a](FSharpList`1 l, Int32 n) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\prim-types.fs:line 3649
   at Microsoft.FSharp.Collections.FSharpList`1.get_Item(Int32 index) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\prim-types.fs:line 3699
   at FSI_0001.main()
```

The throwing function is ```fail()```. Why is neither ```fail()``` nor ```start()``` listed in the stacktrace?
Compare this with the console app:
```
let fail () = [].[5]
let start () = fail ()
[<EntryPoint>]
let main argv =
    try
        printfn $"{start()}"
    with
    | e ->
        printfn $"{e}"
    0
```

```dotnet run``` outputs correctly:
```
System.ArgumentException: The index was outside the range of elements in the list. (Parameter 'n')
   at Microsoft.FSharp.Collections.PrivateListHelpers.nth[a](FSharpList`1 l, Int32 n) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\prim-types.fs:line 3649
   at Microsoft.FSharp.Collections.FSharpList`1.get_Item(Int32 index) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\prim-types.fs:line 3699
   at Program.fail[a]() in C:\Users\rene\fstest\Program.fs:line 1
   at Program.start[a]() in C:\Users\rene\fstest\Program.fs:line 2
   at Program.main(String[] argv) in C:\Users\rene\fstest\Program.fs:line 6
```

**Comment by TIHan** [comment]
At first glance, I think the reason is because the functions are being inlined; that's why they don't show up in the stack-trace.

I did try using `dotnet fsi --optimize- --debug+ script.fsx` but it still looks like it inlines it anyway? Especially with the command line options set, we should not auto-inline them.

**Comment by reneederer** [comment]
Thank you for working on this. It would be useful to have a line number in the stack-trace as well (instead of just "at FSI_0001.main()").

**Comment by dsyme** [comment]
This is by design because of tailcalls.

Use the following to get the debug stack trace:

    dotnet fsi --optimize- --debug+ --tailcalls- g.fsx

**Comment by reneederer** [comment]
It would be helpful to have the line number where the exception occurred.

```dotnet fsi --optimize- --debug+ --tailcalls- g.fsx``` currently prints
```
System.ArgumentException: The index was outside the range of elements in the list. (Parameter 'n')
   at Microsoft.FSharp.Collections.PrivateListHelpers.nth[a](FSharpList`1 l, Int32 n) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\prim-types.fs:line 3698
   at Microsoft.FSharp.Collections.FSharpList`1.get_Item(Int32 index) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\prim-types.fs:line 3748
   at FSI_0001.fail[a]()
   at FSI_0001.start[a]()
   ```

**Comment by cordae6** [comment]
REP: Connie P.D.F sample

590FTL
The format is on the desktop please
