### ISSUE TITLE
printf tests failing in `main`

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#11623]
printf tests are randomly (because we run a random subset of the tests every time) failing in `main`:

For example:
```
Failed printf [23 s]
  Error Message:
   Error running command 'D:\workspace\_work\1\s\tests\FSharp.Test.Utilities\..\..\.dotnet\dotnet.exe' with args 'run -f net472' in directory 'D:\workspace\_work\1\s\artifacts\Temp\FSharp.Cambridge\dlpi1chu.gdt'.
---- stdout below --- 
Running a random subset of tests.  Set "runEveryTest" to true to run all tests
...

Test Failed

---- stderr below --- 
 NO: test cewoui2.: expected 
	'FFFFFFFFFFFFFFFF' but produced 
	'8000000000000000'
 . ERRORLEVEL 1
  Stack Trace:
     at TestFramework.checkResult(CmdResult result) in D:\workspace\_work\1\s\tests\FSharp.Test.Utilities\TestFramework.fs:line 381
   at SingleTest.executeFsc@273.Invoke(String testCompilerVersion, String targetFramework) in D:\workspace\_work\1\s\tests\fsharp\single-test.fs:line 281
   at SingleTest.executeSingleTestBuildAndRun@220.Invoke(OutputType outputType, String compilerType, String targetFramework, Boolean optimize, Boolean buildOnly) in D:\workspace\_work\1\s\tests\fsharp\single-test.fs:line 283
   at SingleTest.singleTestBuildAndRunCore(TestConfig cfg, String copyFiles, Permutation p, String languageVersion) in D:\workspace\_work\1\s\tests\fsharp\single-test.fs:line 312
   at SingleTest.singleTestBuildAndRunVersion(String dir, Permutation p, String version) in D:\workspace\_work\1\s\tests\fsharp\single-test.fs:line 378
   at FSharp.Tests.Core.singleTestBuildAndRunVersion@34-1.Invoke(String dir, Permutation p, String version) in D:\workspace\_work\1\s\tests\fsharp\tests.fs:line 34
   at FSharp.Tests.Core.CoreTests.printf() in D:\workspace\_work\1\s\tests\fsharp\tests.fs:line 199
```
(from https://dev.azure.com/dnceng/public/_build/results?buildId=1167280&view=logs&j=966222a4-f29d-5ec0-88cc-1b798728906e&t=052eabf8-67e2-5f29-745c-00cc34aa0e02)

Here's the test which is failing: https://github.com/dotnet/fsharp/blob/main/tests/fsharp/core/printf/test.fsx#L140

Is it a typo in the test?
Since `Int64.MinValue.ToString("X", CultureInfo.InvariantCulture)` should be equal to `8000000000000000` and not `FFFFFFFFFFFFFFFF`.

Shall we also enable all printf tests? I wonder how expensive will it be?

**Comment by vzarytovskii** [comment]
@Happypig375 sorry, for tagging you earlier, for some reason I thought it was related to the formatter work you were doing earlier :(

**Comment by Happypig375** [comment]
It's okay, I was relying on the CI since I did all edits on the web editor (I need a better computer to handle this solution). Guess I can't really rely too much on it after all.
