### ISSUE TITLE
System.NullReferenceException using task CE

### ISSUE THREAD

**Issue by JonCanning** [dotnet/fsharp#12469]
Sample `fsx`, I'm running dotnet 6.0.100 on OSX
```
open System.Threading.Tasks

let test (f: _ -> Task<_>) =
  task {
    let y =
      Map.ofSeq [ 1, 1 ] |> Map.toArray |> Array.map fst

    let! _ = f 1

    for x in y do
      ()
  }

test(Task.FromResult).Wait()
```

Exception is thrown
```
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FSI_0001.test@4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at <StartupCode$FSI_0001>.$FSI_0001.main@()
Stopped due to error
```

This works with Ply, and I it works with the new task CE by moving the `let! _` above the `let m`

**Comment by vzarytovskii** [comment]
Hey @JonCanning, thanks for reporting this, it seems, that the issue is a duplicate of https://github.com/dotnet/fsharp/issues/12359, which was fixed in https://github.com/dotnet/fsharp/pull/12374 and should be in the next dev17.1 and dotnet releases, there are some workarounds mentioned in the original issue: https://github.com/dotnet/fsharp/issues/12359 in a meantime.

Results from the `main` branch:
```fsharp
Microsoft (R) F# Interactive version 12.0.0.0 for F# 6.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> open System.Threading.Tasks
-
- let test (f: _ -> Task<_>) =
-   task {
-     let y =
-       Map.ofSeq [ 1, 1 ] |> Map.toArray |> Array.map fst
-
-     let! _ = f 1
-
-     for x in y do
-       ()
-   }
-
- test(Task.FromResult).Wait();;
val test:
  f: (int -> System.Threading.Tasks.Task<'a>)
    -> System.Threading.Tasks.Task<unit>
val it: unit = ()
```

I'm going to close at as a duplicate of https://github.com/dotnet/fsharp/issues/12359.
