### ISSUE TITLE
FSharpCodeLensService crash

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12627]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/FSharpCodeLensService-crash/1557752)._

---
In VS2022, I have noticed the following error in the "F# Language Service" output window.

```
[F#] [ERROR 10:05:21 AM] Context: Buffer Changed
Exception Message: The option value was None
Parameter name: option
Stack Trace:    at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\option.fs:line 11
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService[Redacted]@[Redacted]Unit _arg15) in D:\workspace\_work\1\s\vsintegration\src\FSharp.Editor\CodeLens\FSharpCodeLensService.fs:line 156
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 464
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 105
```

---
#### Feedback Bot on 10/19/2021, 06:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by psfinaki** [comment]
Most likely related to some bad programming practices [here](https://github.com/dotnet/fsharp/blob/6735c6fea5287a00279c2c560ee8b786c9b54c29/vsintegration/src/FSharp.Editor/CodeLens/CodeLensProvider.fs#L69).

Will handle this.
