### ISSUE TITLE
TypeLoadException debugging VisualFSharpDebug

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#12732]
**Repro steps**

1. Clone or git clean the fsharp repo and execute build.cmd
3. Open VisualFSharp.sln
4. Set VisualFSharpDebug as the startup project and press F5
5. Open an F# file in the debugged VS instance
6. Press Ctrl-space to trigger Intellisense

**Expected behavior**

Intellisense appears.

**Actual behavior**

No Intellisense appears.
TypeLoadException is shown in the VS toolbar, the XML activity log contains

```
System.TypeLoadException: Declaration referenced in a method implementation cannot be a final method. Type: 'Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionService'. Assembly: 'FSharp.Editor, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
at Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionServiceFactory.Microsoft.CodeAnalysis.Host.Mef.ILanguageServiceFactory.CreateLanguageService(HostLanguageServices hostLanguageServices)
at System.Lazy`1.CreateValue()
at System.Lazy`1.LazyInitValue()
at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.GetService[TLanguageService]()
at Microsoft.CodeAnalysis.Shared.Extensions.ProjectExtensions.GetLanguageService[TLanguageService](Project project)
at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.GetLanguageService[TLanguageService](Document document)
at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CompletionSource.InitializeCompletion(CompletionTrigger trigger, SnapshotPoint triggerLocation, CancellationToken cancellationToken)
at Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Implementation.AsyncCompletionBroker.<>c__DisplayClass116_1.<GetCompletionSources>b__7()
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint[T](Object errorSource, Func`1 call, T valueOnThrow)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)	
```

**Related information**

Win 10
VS 17.2 Preview 1
```
>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\

Host (useful for support):
  Version: 7.0.0-preview.2.22102.1
  Commit:  6527b7fe83

.NET SDKs installed:
  6.0.200 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.2.22103.2 [C:\Program Files\dotnet\sdk]
```

**Comment by kerams** [comment]
This prevents me from contributing, so really annoying without a fix or workaround.

**Comment by dsyme** [comment]
@kerams reports this failing

* "main" + Visual Studio 17.2 preview + VisualFSharpDebug + Debug

All of the following also failed for me:

* "main" + Visual Studio 17.1 + VisualFSharpDebug + Debug
* "main" + Visual Studio 17.1 + VisualFSharpFull + Debug
* "main" + Visual Studio 17.1 + VisualFSharpFull + Release



```
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'Microsoft.CodeAnalysis.ExternalAccess.FSharp.Completion.FSharpCompletionOptions' from assembly 'Microsoft.CodeAnalysis.ExternalAccess.FSharp, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
  Source=FSharp.Editor
  StackTrace:
   at Microsoft.VisualStudio.FSharp.Editor.FSharpLanguageService.Initialize() in C:\GitHub\dsyme\fsharp\vsintegration\src\FSharp.Editor\LanguageService\LanguageService.fs:line 307
   at Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.AbstractLanguageService`2.Setup() in /_/src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractLanguageService`2.cs:line 108
   at Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.AbstractPackage`2.<<InitializeAsync>b__4_0>d.MoveNext() in /_/src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractPackage`2.cs:line 65
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\clr\src\BCL\system\runtime\exceptionservices\exceptionservicescommon.cs:line 133

  This exception was originally thrown at this call stack:
    Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.AbstractLanguageService<TPackage, TLanguageService>.Setup() in AbstractLanguageService`2.cs
    Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.AbstractPackage<TPackage, TLanguageService>.InitializeAsync.AnonymousMethod__4_0(System.Threading.CancellationToken) in AbstractPackage`2.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in exceptionservicescommon.cs
```

**Comment by dsyme** [comment]
@KevinRansom @vzarytovskii I'm concerned this may represent some kind of bug in the product.  Or maybe it's a mismatch between `main` and the versions of VS being used.  Either way it's blocking contribution

**Comment by dsyme** [comment]
@KevinRansom @vzarytovskii Ping on this, it's a blocking issue for contributing to Visual F# Tools

**Comment by vzarytovskii** [comment]
> @KevinRansom @vzarytovskii Ping on this, it's a blocking issue for contributing to Visual F# Tools

Yeah, it's a weird issue, I've been looking at it on Friday. Gonna chat with Kevin on Monday and see how we can fix it

**Comment by KevinRansom** [comment]
So ... this is what is supposed to work:


Retail **MUST** work with _main_.   Preview **MAY** work with _main_.

Preview **MAY** work with _release/dev17.X_.  Retail **MAY** work with _release/dev17.X_

given that internally we mainly work with preview some crap may have got in.  I will try to fix it.

**Comment by kerams** [comment]
If it's any help, I saw this the first time while working on https://github.com/dotnet/fsharp/pull/12351. Not initially in November, but certainly in mid December.
