### ISSUE TITLE
Release mode debug info is needlessly off

### ISSUE THREAD

**Issue by dsyme** [dotnet/fsharp#12748]
It looks like our release mode code - which is also used by F# Interactive by default - can easily be fixed to improve debugging. 

For example, take this indicative code below and compare the call stacks

Debug:
```
C:\GitHub\dsyme\fsharp>artifacts\bin\fsi\Debug\net472\fsi.exe --optimize- a.fsx
System.Exception: fail
   at FSI_0001.f() in C:\GitHub\dsyme\fsharp\a.fsx:line 12
   at FSI_0001.g() in C:\GitHub\dsyme\fsharp\a.fsx:line 20
   at <StartupCode$FSI_0001>.$FSI_0001.main@() in C:\GitHub\dsyme\fsharp\a.fsx:line 23
Stopped due to error
```
Release:
```
C:\GitHub\dsyme\fsharp>artifacts\bin\fsi\Debug\net472\fsi.exe a.fsx
System.Exception: fail
   at FSI_0001.f() in C:\GitHub\dsyme\fsharp\a.fsx:line 7
   at FSI_0001.g() in C:\GitHub\dsyme\fsharp\a.fsx:line 19
   at <StartupCode$FSI_0001>.$FSI_0001.main@() in C:\GitHub\dsyme\fsharp\a.fsx:line 4
Stopped due to error
```
The code (or anything similar):
```
let x = 1 + 1

let f() : int = 
   printfn "hello"
   printfn "hello"
   printfn "hello"
   printfn "hello"
   printfn "hello"
   failwith "fail"

let g() =
   printfn "hello"
   printfn "hello"
   printfn "hello"
   printfn "hello"
   printfn "hello"
   f()

g() 
```

**Comment by dsyme** [comment]
The above were taken with .NET Framework.  These stack traces are much better on .NET Core.  I'm going to close this.

Optimized:
```
C:\GitHub\dsyme\fsharp>dotnet artifacts\bin\fsi\Debug\net5.0\fsi.dll  --optimize+ a.fsx
System.Exception: fail
   at FSI_0001.f() in C:\GitHub\dsyme\fsharp\a.fsx:line 12
   at FSI_0001.g() in C:\GitHub\dsyme\fsharp\a.fsx:line 20
   at <StartupCode$FSI_0001>.$FSI_0001.main@() in C:\GitHub\dsyme\fsharp\a.fsx:line 23
Stopped due to error
```
Debug (identical)
```
C:\GitHub\dsyme\fsharp>dotnet artifacts\bin\fsi\Debug\net5.0\fsi.dll  --optimize- a.fsx
System.Exception: fail
   at FSI_0001.f() in C:\GitHub\dsyme\fsharp\a.fsx:line 12
   at FSI_0001.g() in C:\GitHub\dsyme\fsharp\a.fsx:line 20
   at <StartupCode$FSI_0001>.$FSI_0001.main@() in C:\GitHub\dsyme\fsharp\a.fsx:line 23
Stopped due to error
```

**Comment by dsyme** [comment]
And for code compiled from a .ENT 6.0 program in Visual Studio:

Release:
```
C:\GitHub\dsyme\fsharp>dotnet C:\Users\dsyme\source\repos\ConsoleApp12\ConsoleApp12\bin\Release\net6.0\ConsoleApp12.dll
Unhandled exception. System.Exception: fail
   at Program.f() in C:\Users\dsyme\source\repos\ConsoleApp12\ConsoleApp12\Program.fs:line 9
   at Program.g() in C:\Users\dsyme\source\repos\ConsoleApp12\ConsoleApp12\Program.fs:line 17
   at <StartupCode$ConsoleApp12>.$Program.main@() in C:\Users\dsyme\source\repos\ConsoleApp12\ConsoleApp12\Program.fs:line 19
```
Debug (identical):
```
C:\GitHub\dsyme\fsharp>dotnet C:\Users\dsyme\source\repos\ConsoleApp12\ConsoleApp12\bin\Debug\net6.0\ConsoleApp12.dll
Unhandled exception. System.Exception: fail
   at Program.f() in C:\Users\dsyme\source\repos\ConsoleApp12\ConsoleApp12\Program.fs:line 9
   at Program.g() in C:\Users\dsyme\source\repos\ConsoleApp12\ConsoleApp12\Program.fs:line 17
   at <StartupCode$ConsoleApp12>.$Program.main@() in C:\Users\dsyme\source\repos\ConsoleApp12\ConsoleApp12\Program.fs:line 19
```

**Comment by dsyme** [comment]
So one lesson here is that for now we should only focus on release mode on .NET Core.
