### ISSUE TITLE
error FS0073: internal error: tcrefOfAppTy (Failure) - using latest vs 17.3.2

### ISSUE THREAD

**Issue by MarkNicholls** [dotnet/fsharp#13799]
I'm getting this error

    error FS0073: internal error: tcrefOfAppTy (Failure) 

reported on this code

```
    module AttributeExtensions     // 1 tcrefOfAppTy  error reported here 

    open Attributes
    open System.Runtime.CompilerServices

    type ``Children``<'a> = abstract member ``Children`` : Unit -> 'a
    
    [<Extension>]
    type Extensions =
        [<Extension>]
        static member Children<'A, 'B when 'A :> ``Children``<'B>> (this: 'A) = 
            this.Children()
    
    let f2 a =             // 1 tcrefOfAppTy error reported here
        a.Children()     // 2 tcrefOfAppTy errors reported here.

```
apologies for the strange code, this is part of a much much bigger project with literally hundreds if not thousands of types (I'm wondering if that's the problem somehow), and this is the simplest example I can give.

This code DID used to compile on azure devops on a "windows-2019" box, with dotnet core 3.x, against F# 5.0

It doesnt compile (this project) on "windows-2022" box, since ive upgraded it to dotnetcore 6.0, F# 5, using a fake build script.

    MSBuild version 17.3.0+f67e3d35e for .NET Framework

It fails using dotnetcore 6.0.400 and 6.0.302 (I downgraded based on a hunch from a similar reported issue).

This code did compile in visual studio 2022, on my laptop, windows 11 pro.

And also the same fake script works, though my machine has this

    Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework

and runs visual studio professional.

The devops logs contain this:

```
    Unhandled Exception: System.Exception: tcrefOfAppTy
    2022-08-29T10:32:08.1995442Z             at FSharp.Compiler.TypedTreeOps.tcrefOfAppTy(TcGlobals g, TType ty) in D:\a\_work\1\s\src\Compiler\TypedTree\TypedTreeOps.fs:line 877
    2022-08-29T10:32:08.1997298Z             at FSharp.Compiler.AttributeChecking.CheckMethInfoAttributes[a](TcGlobals g, Range m, FSharpOption`1 tyargsOpt, MethInfo minfo) in D:\a\_work\1\s\src\Compiler\Checking\AttributeChecking.fs:line 403
    2022-08-29T10:32:08.1999466Z             at FSharp.Compiler.MethodCalls.MethInfoChecks[a](TcGlobals g, ImportMap amap, Boolean isInstance, FSharpOption`1 tyargsOpt, FSharpList`1 objArgs, AccessorDomain ad, Range m, MethInfo minfo) in D:\a\_work\1\s\src\Compiler\Checking\MethodCalls.fs:line 1199
    2022-08-29T10:32:08.2003101Z             at FSharp.Compiler.CheckExpressions.TcMethodApplication(Boolean isCheckingAttributeCall, TcFileState cenv, TcEnv env, UnscopedTyparEnv tpenv, FSharpOption`1 tyArgsOpt, FSharpList`1 objArgs, Range mMethExpr, Range mItem, String methodName, FSharpOption`1 objTyOpt, AccessorDomain ad, Mutates mut, Boolean isProp, FSharpList`1 calledMethsAndProps, AfterResolution afterResolution, ValUseFlag isSuperInit, FSharpList`1 curriedCallerArgs, OverallTy exprTy, FSharpList`1 delayed) in D:\a\_work\1\s\src\Compiler\Checking\CheckExpressions.fs:line 9661
    2022-08-29T10:32:08.2007667Z             at FSharp.Compiler.CheckExpressions.TcMethodApplicationThen(TcFileState cenv, TcEnv env, OverallTy overallTy, FSharpOption`1 objTyOpt, UnscopedTyparEnv tpenv, FSharpOption`1 callerTyArgs, FSharpList`1 objArgs, Range m, Range mItem, String methodName, AccessorDomain ad, Mutates mut, Boolean isProp, FSharpList`1 meths, AfterResolution afterResolution, ValUseFlag isSuperInit, FSharpList`1 args, ExprAtomicFlag atomicFlag, FSharpList`1 delayed) in D:\a\_work\1\s\src\Compiler\Checking\CheckExpressions.fs:line 9169

```
I can supply more information if needed.

For the moment I will comment out these lines out (there part of an experiment).

**Comment by MarkNicholls** [comment]
I looked at that one it says:

Changing the .NET SDK to 6.0.302 (and changing the <TargetFramework>) does allow this sample to compile.

thats why I tried downgrading to 6.0.302

it still doesnt work

**Comment by vzarytovskii** [comment]
> thats why I tried downgrading to 6.0.302

It should help (just checked it) when using only .NET SDK, and not VS msbuild. Since the bug was introduced in `6.0.400` and latest VS17.3, I think, if you have installed VS and use its SDK, it will fail.

> it still doesnt work

It was also fixed in the VS 17.4, which is in preview now.

We are trying to do the servicing release for 17.3.x and 6.0.xxx, but there's no ETA for now.

**Comment by MarkNicholls** [comment]
ok, its not core functionality for me, so I'll wait for 17.4 and let u know if that doesnt fix it.
Thanks v much
