### ISSUE TITLE
NullReferenceException in task workflow

### ISSUE THREAD

**Issue by forki** [dotnet/fsharp#14002]
We have some healthcheck code with task workflows and the sometimes crash with NullReferenceException in some FSharp.Core code. I could not find the root cause yet, but I assume something in the task workflow compilation went wrong.

```
2022-09-30T05:31:27.174067241Z [40m [32minfo [39m [22m [49m: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
2022-09-30T05:31:27.174100942Z       Executed endpoint 'Health checks'
2022-09-30T05:31:27.174773144Z [41m [30mfail [39m [22m [49m: Giraffe.Middleware.GiraffeErrorHandlerMiddleware[0]
2022-09-30T05:31:27.174789344Z       An unhandled exception has occurred while executing the request.
2022-09-30T05:31:27.174794745Z       System.NullReferenceException: Object reference not set to an instance of an object.
2022-09-30T05:31:27.175450247Z          at Microsoft.FSharp.Core.CompilerServices.ResumableCode.TryFinallyCompensateDynamic[TData](ResumableStateMachine`1& sm, ResumptionFunc`1 mf, FSharpOption`1 savedExn) in D:\a\_work\1\s\src\FSharp.Core\resumable.fs:line 300
2022-09-30T05:31:27.175911749Z          at ServerCode.HealthChecks.clo@78-88.Invoke(ResumableStateMachine`1& sm)
2022-09-30T05:31:27.175928149Z          at <StartupCode$FSharp-Core>.$Tasks.resumptionInfo@171.MoveNext(ResumableStateMachine`1& sm) in D:\a\_work\1\s\src\FSharp.Core\tasks.fs:line 193
2022-09-30T05:31:27.175934449Z       --- End of stack trace from previous location ---
2022-09-30T05:31:27.176169450Z          at Prometheus.CollectorRegistry.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
2022-09-30T05:31:27.176662752Z          at ServerCode.HealthChecks.response@21.MoveNext() in /home/gitlab-runner/builds/1-vFfjTk/0/a-team/eCarApp/src/eCarCloud/HealthChecks.fs:line 30
2022-09-30T05:31:27.176683052Z          at Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckMiddleware.InvokeAsync(HttpContext httpContext)
2022-09-30T05:31:27.176878353Z          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2022-09-30T05:31:27.176893753Z          at Giraffe.Middleware.Invoke@63-1.MoveNext()
2022-09-30T05:31:27.177142354Z [40m [32minfo [39m [22m [49m: Microsoft.AspNetCore.Hosting.Diagnostics[2]
2022-09-30T05:31:27.177157854Z       Request finished HTTP/1.1 GET http://m8m-portal-staging.azurewebsites.net/metrics - 0 - 500 55 application/json;+charset=utf-8 240.8405ms
2022-09-30T05:31:27.211749099Z [40m [32minfo [39m [22m [49m: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
2022-09-30T05:31:27.211778599Z       Executed endpoint 'Health checks'
2022-09-30T05:31:27.212076800Z [41m [30mfail [39m [22m [49m: Giraffe.Middleware.GiraffeErrorHandlerMiddleware[0]
2022-09-30T05:31:27.212241301Z       An unhandled exception has occurred while executing the request.
2022-09-30T05:31:27.212252901Z       System.NullReferenceException: Object reference not set to an instance of an object.
2022-09-30T05:31:27.212644202Z          at Microsoft.FSharp.Core.CompilerServices.ResumableCode.TryFinallyCompensateDynamic[TData](ResumableStateMachine`1& sm, ResumptionFunc`1 mf, FSharpOption`1 savedExn) in D:\a\_work\1\s\src\FSharp.Core\resumable.fs:line 300
2022-09-30T05:31:27.212885603Z          at ServerCode.HealthChecks.clo@78-88.Invoke(ResumableStateMachine`1& sm)
2022-09-30T05:31:27.212900804Z          at <StartupCode$FSharp-Core>.$Tasks.resumptionInfo@171.MoveNext(ResumableStateMachine`1& sm) in D:\a\_work\1\s\src\FSharp.Core\tasks.fs:line 193
2022-09-30T05:31:27.212906704Z       --- End of stack trace from previous location ---
2022-09-30T05:31:27.213123204Z          at Prometheus.CollectorRegistry.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
2022-09-30T05:31:27.213318705Z          at ServerCode.HealthChecks.response@21.MoveNext() in /home/gitlab-runner/builds/1-vFfjTk/0/a-team/eCarApp/src/eCarCloud/HealthChecks.fs:line 30
2022-09-30T05:31:27.213333305Z          at Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckMiddleware.InvokeAsync(HttpContext httpContext)
2022-09-30T05:31:27.213525706Z          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2022-09-30T05:31:27.213540906Z          at Giraffe.Middleware.Invoke@63-1.MoveNext()
2022-09-30T05:31:27.219065529Z [40m [32minfo [39m [22m [49m: Microsoft.AspNetCore.Hosting.Diagnostics[2]
2022-09-30T05:31:27.219084529Z       Request finished HTTP/1.1 GET http://m8m-portal-staging.azurewebsites.net/metrics - - - 500 55 application/json;+charset=utf-8 290.0342ms
```

![image](https://user-images.githubusercontent.com/57396/193200282-60e3489f-256b-47db-ac02-756b01ca6780.png)

I think the code looks absolutely normal

**Comment by edgarfgp** [comment]
Seems similar  to https://github.com/dotnet/fsharp/issues/13657

**Comment by vzarytovskii** [comment]
Which SDK version was used to build it, and what runtime version is it running on?

**Comment by forki** [comment]
It's running on the latest version of FSharp.Core and .NET SDK 6.0.401. Everything is on latest.

**Comment by forki** [comment]
so I looked briefly at the code in resumptionInfo:

![image](https://user-images.githubusercontent.com/57396/194538127-aff6b444-92e9-48c3-8a55-7a75d3cae564.png)


so there is indeed some explicit null handling.

**Comment by T-Gro** [comment]
@forki , could you please send a text-based repro to test this on?
We believe it might have been fixed in the meantime.

**Comment by T-Gro** [comment]
(in 7.0.100)

**Comment by forki** [comment]
I don't have that repro. It's deep hidden in our production app

Tomas Grosup ***@***.***> schrieb am Mo., 21. Nov. 2022,
18:38:

**Comment by T-Gro** [comment]
Ok. And is trying on latest SDK an option for you?

**Comment by vzarytovskii** [comment]
> Ok. And is trying on latest SDK an option for you?

Actually, looking at latest fixes around resumable code, I don't think it was actually fixed. We'll probably need to try and figure out repro (it's around tryfinally code).

**Comment by vzarytovskii** [comment]
I've hit it when moving NodeCodeBuilder to resumable code

**Comment by dsyme** [comment]
The fact `TryFinallyCompensateDynamic` is being hit is also of interest as it indicates state machine compilation may have failed
```
2022-09-30T05:31:27.175450247Z          at Microsoft.FSharp.Core.CompilerServices.ResumableCode.TryFinallyCompensateDynamic[TData](ResumableStateMachine`1& sm, ResumptionFunc`1 mf, FSharpOption`1 savedExn) in D:\a\_work\1\s\src\FSharp.Core\resumable.fs:line 300
```

**Comment by dsyme** [comment]
Although there is a "raise" that rethrows an exception in that method, so the exception could be happening earlier
