### ISSUE TITLE
'T.Zero and GenericZero give different results

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#14286]
![20221109_221524.jpg](https://user-images.githubusercontent.com/1260985/200943485-22c9f2a7-44bb-464d-93b7-ef0d72a8d8bf.jpg)

**Comment by wraikny** [comment]
`GenericZero` is statically optimized for primitive types. I guess it is caused by this difference, however, I'm not familiar with compilers. Thanks for opening issue 🙏.

https://github.com/dotnet/fsharp/blob/575d5e7519fda9621730a0fceeb5334b9bc7c584/src/FSharp.Core/prim-types.fs#L2501

**Comment by vzarytovskii** [comment]
Okay, two findings, given the following code:
```fsharp
type Zero<'T when 'T: (static member Zero: 'T)> = 'T
let inline zero<'T when Zero<'T>> =
    let u = Unchecked.defaultof<'T>
    let g = LanguagePrimitives.GenericZero<'T>
    let z = 'T.Zero
    let gz = 'T.get_Zero()

    printfn "%A %A %A %A" u g z gz

zero<int>
zero<float>
```
`dotnet run` results in the following:
```
0 0 1863393088 0
0.0 0.0 1.114968446e-311 0.0
```

So, the problem is the property.

**However**, if you run it as fsx script, you get the following:
```
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at <StartupCode$FSI_0001>.$FSI_0001.main@()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
We emit the following IL:
```csharp
.class nested assembly auto ansi sealed serializable beforefieldinit clo@6
	extends class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<class [FSharp.Core]Microsoft.FSharp.Core.Unit, int32>
{
	// Fields
	.field assembly static initonly class Program/clo@6 @_instance

	// Methods
	.method assembly specialname rtspecialname 
		instance void .ctor () cil managed 
	{
		.custom instance void [System.Runtime]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = (
			01 00 00 00
		)
		.custom instance void [System.Runtime]System.Diagnostics.DebuggerNonUserCodeAttribute::.ctor() = (
			01 00 00 00
		)
		// Method begins at RVA 0x20b8
		// Header size: 1
		// Code size: 7 (0x7)
		.maxstack 8

		IL_0000: ldarg.0
		IL_0001: call instance void class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<class [FSharp.Core]Microsoft.FSharp.Core.Unit, int32>::.ctor()
		IL_0006: ret
	} // end of method clo@6::.ctor

	.method public strict virtual 
		instance int32 Invoke (
			class [FSharp.Core]Microsoft.FSharp.Core.Unit arg00@
		) cil managed 
	{
		// Method begins at RVA 0x20c0
		// Header size: 1
		// Code size: 8 (0x8)
		.maxstack 8

		IL_0000: ldarg.1
		IL_0001: pop
		IL_0002: call !!0 [FSharp.Core]Microsoft.FSharp.Core.LanguagePrimitives::GenericZeroDynamic<int32>()
		IL_0007: ret
	} // end of method clo@6::Invoke

	.method private specialname rtspecialname static 
		void .cctor () cil managed 
	{
		// Method begins at RVA 0x20cc
		// Header size: 12
		// Code size: 11 (0xb)
		.maxstack 10

		IL_0000: newobj instance void Program/clo@6::.ctor()
		IL_0005: stsfld class Program/clo@6 Program/clo@6::@_instance
		IL_000a: ret
	} // end of method clo@6::.cctor

} // end of class clo@6

```
and
```csharp
.method public static 
	void main@ () cil managed 
{
	// Method begins at RVA 0x20e4
	// Header size: 12
	// Code size: 29 (0x1d)
	.maxstack 4
	.entrypoint
	.locals init (
		[0] int32
	)

	IL_0000: ldsfld class Program/clo@6 Program/clo@6::@_instance
	IL_0005: stloc.0
	IL_0006: ldstr "%A"
	IL_000b: newobj instance void class [FSharp.Core]Microsoft.FSharp.Core.PrintfFormat`5<class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<int32, class [FSharp.Core]Microsoft.FSharp.Core.Unit>, class [System.Runtime]System.IO.TextWriter, class [FSharp.Core]Microsoft.FSharp.Core.Unit, class [FSharp.Core]Microsoft.FSharp.Core.Unit, int32>::.ctor(string)
	IL_0010: call !!0 [FSharp.Core]Microsoft.FSharp.Core.ExtraTopLevelOperators::PrintFormatLine<class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<int32, class [FSharp.Core]Microsoft.FSharp.Core.Unit>>(class [FSharp.Core]Microsoft.FSharp.Core.PrintfFormat`4<!!0, class [System.Runtime]System.IO.TextWriter, class [FSharp.Core]Microsoft.FSharp.Core.Unit, class [FSharp.Core]Microsoft.FSharp.Core.Unit>)
	IL_0015: ldloc.0
	IL_0016: callvirt instance !1 class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<int32, class [FSharp.Core]Microsoft.FSharp.Core.Unit>::Invoke(!0)
	IL_001b: pop
	IL_001c: ret
} // end of method $Program::main@

```

**Comment by vzarytovskii** [comment]
And this, when getter is getting called directly:
```csharp
.method public static 
	void main@ () cil managed 
{
	// Method begins at RVA 0x20b8
	// Header size: 12
	// Code size: 25 (0x19)
	.maxstack 4
	.entrypoint
	.locals init (
		[0] int32
	)

	IL_0000: ldc.i4.0
	IL_0001: stloc.0
	IL_0002: ldstr "%A"
	IL_0007: newobj instance void class [FSharp.Core]Microsoft.FSharp.Core.PrintfFormat`5<class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<int32, class [FSharp.Core]Microsoft.FSharp.Core.Unit>, class [System.Runtime]System.IO.TextWriter, class [FSharp.Core]Microsoft.FSharp.Core.Unit, class [FSharp.Core]Microsoft.FSharp.Core.Unit, int32>::.ctor(string)
	IL_000c: call !!0 [FSharp.Core]Microsoft.FSharp.Core.ExtraTopLevelOperators::PrintFormatLine<class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<int32, class [FSharp.Core]Microsoft.FSharp.Core.Unit>>(class [FSharp.Core]Microsoft.FSharp.Core.PrintfFormat`4<!!0, class [System.Runtime]System.IO.TextWriter, class [FSharp.Core]Microsoft.FSharp.Core.Unit, class [FSharp.Core]Microsoft.FSharp.Core.Unit>)
	IL_0011: ldloc.0
	IL_0012: callvirt instance !1 class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<int32, class [FSharp.Core]Microsoft.FSharp.Core.Unit>::Invoke(!0)
	IL_0017: pop
	IL_0018: ret
} // end of method $Program::main@

```

**Comment by En3Tho** [comment]
As far as I know Int32 or Float do not have a native Zero property. It's hidden by INumberBase like
```csharp static int INumberBase<int>.Zero => Zero;
```
I'm not sure what F# compiler is calling here

**Comment by vzarytovskii** [comment]
> As far as I know Int32 or Float do not have a native Zero property. It's hidden by INumberBase like
> 
> ```cs
>  static int INumberBase<int>.Zero => Zero;
> ```
> 
> I'm not sure what F# compiler is calling here

Calling getter explicitly works, the problem is with property

**Comment by En3Tho** [comment]
Yeah, but can you please explain why get_Zero works even if int32 doesn't have this property? I mean not natively.

**Comment by vzarytovskii** [comment]
> Yeah, but can you please explain why get_Zero works even if int32 doesn't have this property? I mean not natively.

It has it via the interface

**Comment by En3Tho** [comment]
Yes. But there is no interface in the call. It's just type. Does SRTP take Interfaces in count too when trying to find target? I didn't think it did..

**Comment by vzarytovskii** [comment]
> Yes. But there is no interface in the call. It's just type. Does SRTP take Interfaces in count too when trying to find target? I didn't think it did..

Things like `get_Zero` have special treatment, as .NET types can have those implicitly.

**Comment by En3Tho** [comment]
![image](https://user-images.githubusercontent.com/37334640/201071114-298f122e-86bd-4d3a-b7cf-2e498800c26a.png)
This is what I meant

> Things like get_Zero have special treatment, as .NET types can have those implicitly.
Oh, I see now. Thanks. This is totally unexpected.

**Comment by vzarytovskii** [comment]
Funny enough, it doesn't reproduce with custom property:
```fsharp
type Foo = 
    static member Bar = 1

type HasBar<'T when 'T: (static member Bar: int)> = 'T
let inline bar<'T when HasBar<'T>> =
    let z = 'T.Bar

    printfn "%A" z

bar<Foo>
```

**Comment by dsyme** [comment]
The F# constraint solver solves these as builtin solutions.

**Comment by dsyme** [comment]
Something is going wrong in the codegen for those
