### ISSUE TITLE
The compiler crashes when trying to use the code analyzer

### ISSUE THREAD

**Issue by arthurgubaidullin** [dotnet/fsharp#14680]
I tried to write an application using this guide. Everything works, but renaming variables in VS Code does not work. The compiler crashes. I am using mac.

Refactoring functions do not work on any projects because of the compiler!

Why write about editor support if there is none?

**Repro steps**

1. Use mac
2. Use vs code
3. Use any f# project
4. Try to rename function

**Expected behavior**

The refactoring functions should work.

**Actual behavior**

Output of compiler:
```text
[09:40:51.349 ERR] [Commands] Failed findReferencesForSymbolInFile with /Users/user/Projects/experiment-with-dotnet-and-fsharp/src/App/obj/Debug/net6.0/App.AssemblyInfo.fs
System.AggregateException: One or more errors occurred. (The specified file name or path is too long, or a component of the specified path is too long.)
 ---> System.IO.PathTooLongException: The specified file name or path is too long, or a component of the specified path is too long.
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateSharedBackingObjectUsingMemory(MemoryMappedProtections protections, Int64 capacity, HandleInheritability inheritability)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateSharedBackingObject(MemoryMappedProtections protections, Int64 capacity, HandleInheritability inheritability)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateCore(FileStream fileStream, String mapName, HandleInheritability inheritability, MemoryMappedFileAccess access, MemoryMappedFileOptions options, Int64 capacity)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateNew(String mapName, Int64 capacity, MemoryMappedFileAccess access, MemoryMappedFileOptions options, HandleInheritability inheritability)
   at FSharp.Compiler.CodeAnalysis.ItemKeyStoreBuilder.TryBuildAndReset() in D:\a\_work\1\s\src\fsharp\service\ItemKey.fs:line 435
   at <StartupCode$FSharp-Compiler-Service>.$IncrementalBuild.TypeCheck@492-7.Invoke(Tuple`2 _arg11) in D:\a\_work\1\s\src\fsharp\service\IncrementalBuild.fs:line 536
   at FSharp.Compiler.BuildGraph.Bind@53-1.Invoke(T x) in D:\a\_work\1\s\src\fsharp\BuildGraph.fs:line 53
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 465
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
   --- End of inner exception stack trace ---
[09:40:51.356 ERR] [Commands] Failed findReferencesForSymbolInFile with /Users/user/Projects/experiment-with-dotnet-and-fsharp/src/App/Program.fs
System.AggregateException: One or more errors occurred. (The specified file name or path is too long, or a component of the specified path is too long.)
 ---> System.IO.PathTooLongException: The specified file name or path is too long, or a component of the specified path is too long.
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateSharedBackingObjectUsingMemory(MemoryMappedProtections protections, Int64 capacity, HandleInheritability inheritability)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateSharedBackingObject(MemoryMappedProtections protections, Int64 capacity, HandleInheritability inheritability)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateCore(FileStream fileStream, String mapName, HandleInheritability inheritability, MemoryMappedFileAccess access, MemoryMappedFileOptions options, Int64 capacity)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateNew(String mapName, Int64 capacity, MemoryMappedFileAccess access, MemoryMappedFileOptions options, HandleInheritability inheritability)
   at FSharp.Compiler.CodeAnalysis.ItemKeyStoreBuilder.TryBuildAndReset() in D:\a\_work\1\s\src\fsharp\service\ItemKey.fs:line 435
   at <StartupCode$FSharp-Compiler-Service>.$IncrementalBuild.TypeCheck@492-7.Invoke(Tuple`2 _arg11) in D:\a\_work\1\s\src\fsharp\service\IncrementalBuild.fs:line 536
   at FSharp.Compiler.BuildGraph.Bind@53-1.Invoke(T x) in D:\a\_work\1\s\src\fsharp\BuildGraph.fs:line 53
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 465
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
   --- End of inner exception stack trace ---
```

**Known workarounds**

Delete dotnet and forget it like in a bad dream.

**Related information**

* Operating system: mac OS 13.1
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET SDK 6.0.405
* Editing Tools (e.g. Visual Studio Version, Visual Studio): VS Code

**Comment by vzarytovskii** [comment]
VSCode issues should go to https://github.com/fsharp/FsAutoComplete
