### ISSUE TITLE
VS instance launched via VisualFSharpDebug can't open an F# project

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#14727]
Repro steps:
* clone the repo
* call build.cmd
* open the solution in Visual Studio
* run VisualFSharpDebug
* try to open a sample project

<img width="1147" alt="Screenshot 2023-02-10 at 16 30 33" src="https://user-images.githubusercontent.com/3923587/218130622-18054ce5-ce84-40d3-ab17-ef16ec3bb687.png">

```
=====================
2/10/2023 4:23:07 PM
LimitedFunctionality
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.VisualStudio.Shell.Interop.IVsTaskBody.DoWork(IVsTask pTask, UInt32 dwCount, IVsTask[] pParentTasks, Object& pResult)
   at Microsoft.VisualStudio.Services.VsTask.<>c__DisplayClass86_0.<GetCallbackForMultipleParent>b__0(Task`1[] _)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProjectFactory.<CreateProjectContextAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.Workspace.<>c__DisplayClass39_0.<<OnEvaluationUpdateAsync>g__ProcessInitialEvaluationDataAsync|1>d.MoveNext()
===================
```
[ActivityLog.xml.zip](https://github.com/dotnet/fsharp/files/10708981/ActivityLog.xml.zip)

What additional information should I provide?

**Comment by vzarytovskii** [comment]
Seems to be working for me. Which version?

**Comment by auduchinok** [comment]
The latest `main` +
```
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.4.4
```

I'll be happy to look at it together if that could help.

**Comment by vzarytovskii** [comment]
> The latest `main` +
> ```
> Microsoft Visual Studio Professional 2022 (64-bit) - Current
> Version 17.4.4
> ```
> 
> I'll be happy to look at it together if that could help.

I think 17.5 is required for main

**Comment by auduchinok** [comment]
Thanks, I can confirm using 17.5 fixes it. Maybe it could be listed as a requirement in the DEVGUIDE.md?
