### ISSUE TITLE
dotnet fsi --noframework crashes

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#15359]
**Repro steps**

`dotnet fsi --noframework`

**Expected behavior**

fsi launches.

**Actual behavior**

```
For help type #help;;

>

error FS0193: internal error: One or more errors occurred. (Assembly: The system type 'System.Array' was required but no referenced system DLL contained this type, full path: System.Array)

Exception by fsi.exe:
System.Exception: Error creating evaluation session: System.AggregateException: One or more errors occurred. (Assembly: The system type 'System.Array' was required but no referenced system DLL contained this type, full path: System.Array)
 ---> FSharp.Compiler.DiagnosticsLogger+UnresolvedPathReferenceNoRange: Assembly: The system type 'System.Array' was required but no referenced system DLL contained this type, full path: System.Array
   at FSharp.Compiler.TypedTree.CcuThunk.EnsureDerefable(String[] requiringPath) in D:\a\_work\1\s\src\Compiler\TypedTree\TypedTree.fs:line 5526
   at FSharp.Compiler.TypedTree.NonLocalEntityRef.TryDeref(Boolean canError) in D:\a\_work\1\s\src\Compiler\TypedTree\TypedTree.fs:line 3379
   at FSharp.Compiler.TypedTree.EntityRef.Resolve(Boolean canError) in D:\a\_work\1\s\src\Compiler\TypedTree\TypedTree.fs:line 3462
   at FSharp.Compiler.TypedTree.EntityRef.get_Deref() in D:\a\_work\1\s\src\Compiler\TypedTree\TypedTree.fs:line 3474
   at FSharp.Compiler.TcGlobals.TcGlobals..ctor(Boolean compilingFSharpCore, ILGlobals ilg, CcuThunk fslibCcu, String directoryToResolveRelativePaths, Boolean mlCompatibility, Boolean isInteractive, Boolean useReflectionFreeCodeGen, FSharpFunc`2 tryFindSysTypeCcuHelper, Boolean emitDebugInfoInQuotations, Boolean noDebugAttributes, PathMap pathMap, LanguageVersion langVersion) in D:\a\_work\1\s\src\Compiler\TypedTree\TcGlobals.fs:line 1776
   at FSharp.Compiler.CompilerImports.BuildFrameworkTcImports@2476-5.Invoke(FSharpList`1 _arg9) in D:\a\_work\1\s\src\Compiler\Driver\CompilerImports.fs:line 2489
   at FSharp.Compiler.BuildGraph.Bind@61-1.Invoke(T x) in D:\a\_work\1\s\src\Compiler\Facilities\BuildGraph.fs:line 63
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 528
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
```

**Related information**

.NET SDK:
 Version:   8.0.100-preview.4.23260.5

**Comment by KevinRansom** [comment]
Hmm ... that's interesting ...

--noframework should not be allowed for fsi, given that it forces the framework to use the one specified by the runtime it was built with.

I guess the best thing to do is to ignore the switch.

**Comment by kerams** [comment]
Found it in the output of `dotnet fsi --help`

**Comment by KevinRansom** [comment]
@kerams,I am sure you did, the fix includes removing that option.  There is no good scenario where this switch does something usefull on the coreclr version of fsi.  And not really any current valid desktop CLR scenario either.
