### ISSUE TITLE
AddMissingEqualsToTypeDefinitionCodeFixProvider crash

### ISSUE THREAD

**Issue by 0101** [dotnet/fsharp#15685]
This suddenly popped up when editing some code - which wasn't relevant to the code fix (no `type` in sight). But finding the broken `ExactlyOne` should be enough to fix this.

![image](https://github.com/dotnet/fsharp/assets/217092/600b373c-2823-493a-9907-f07e48a048eb)

```
System.ArgumentException : The input sequence contains more than one element.
Parameter name: source
   at Microsoft.FSharp.Collections.SeqModule.ExactlyOne[T](IEnumerable`1 source)
   at async StartupCode$FSharp-Editor(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.CodeFixExtensions.CodeFixContext-RegisterFsharpFix@85(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by vzarytovskii** [comment]
Yeah, as a rule of thumb, we should **not** be throwing in vs, but instead reporting errors using built-in mechanism

**Comment by psfinaki** [comment]
Repro:
```
let f x = 
    match x with
    | _ ->
        let _ = [
            x with
        ]
```

https://github.com/dotnet/fsharp/assets/5451366/4b823b24-2813-4126-801e-361df5ad3b48

Indeed, we have two different FS0010 here:
![image](https://github.com/dotnet/fsharp/assets/5451366/b0ad82d2-b52f-4334-a5d4-3172bd10534e)

**Comment by 0101** [comment]
I would suggest removing all unsafe operations like `exactlyOne`, `head`, etc. From the code fixes (or really anywhere where it can crash in VS) regardless of if the underlying cause is legitimate. Instead of crashing report telemetry so we'll find out about it.

Could be also a nice analyzer to highlight all of these.
