### ISSUE TITLE
UseMutationWhenValueIsMutable code fix crashes at the EOF

### ISSUE THREAD

**Issue by psfinaki** [dotnet/fsharp#15931]
Bangggg:

https://github.com/dotnet/fsharp/assets/5451366/8e686a87-b687-488f-8ee4-4c2233461fcc

Code:
```fsharp
let band = {| Name = "R.E.M." |}

band
```

Stacktrace:
```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.VisualStudio.Text.Implementation.UnaryStringRebuilder.GetChar(Char[] content,Int32 index)
   at <StartupCode$FSharp-Editor>.$UseMutationWhenValueIsMutable.loop@37-8(SourceText sourceText,Char ch,Int32 pos)
   at async StartupCode$FSharp-Editor(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.CodeFixExtensions.CodeFixContext-RegisterFsharpFix@108(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

Regression, caused by the recent changes.

**Comment by psfinaki** [comment]
Okay so it's not because of anon records, it's because of the end of file there.
