### ISSUE TITLE
Test failing on local run

### ISSUE THREAD

**Issue by OwnageIsMagic** [dotnet/fsharp#16065]
**Repro steps**

Provide the steps required to reproduce the problem:

1. `.\Build.cmd -noVisualStudio -testAll /p:UpdateXlfOnBuild=true`

**Actual behavior**
Failed tests

* **EmittedIL.Inlining.List contains inlining**
  I think this failed due to Debug build (not checked actually)

  <details><summary>Details</summary>
    <p>

    ```
  Failed EmittedIL.Inlining.List contains inlining [349 ms]
  Error Message:
   NUnit.Framework.AssertionException :
  ==
  Name: '.method assembly static bool  contains@1<a>(!!a e,'
  
  Expected:        IL_001c:  ldc.r8     (00 00 00 00 00 00 F8 FF)
  Actual:          IL_001c:  call       float64 [FSharp.Core]Microsoft.FSharp.Core.Operators::get_NaN()
  ==
  
  ==
  Name: '.method assembly static bool  contains@1<a>(!!a e,'
  
  Expected:        IL_0025:  ldloc.2
  Actual:          IL_0021:  ldloc.2
  ==
  
  ==
  Name: '.method assembly static bool  contains@1<a>(!!a e,'
  
  Expected:        IL_0026:  ceq
  Actual:          IL_0022:  ceq
  ==
  
  ==
  Name: '.method assembly static bool  contains@1<a>(!!a e,'
  
  Expected:        IL_0028:  brfalse.s  IL_002c
  Actual:          IL_0024:  brfalse.s  IL_0028
  ==
  
  ==
  Name: '.method assembly static bool  contains@1<a>(!!a e,'
  
  Expected:        IL_002a:  ldc.i4.1
  Actual:          IL_0026:  ldc.i4.1
  ==
  
  ==
  Name: '.method assembly static bool  contains@1<a>(!!a e,'
  
  Expected:        IL_002b:  ret
  Actual:          IL_0027:  ret
  ==
  
  ==
  Name: '.method assembly static bool  contains@1<a>(!!a e,'
  
  Expected:        IL_002c:  ldarg.0
  Actual:          IL_0028:  ldarg.0
  ==
  
  ==
  Name: '.method assembly static bool  contains@1<a>(!!a e,'
  
  Expected:        IL_002d:  ldloc.1
  Actual:          IL_0029:  ldloc.1
  ==
  
  ==
  Name: '.method assembly static bool  contains@1<a>(!!a e,'
  
  Expected:        IL_002e:  starg.s    xs1
  Actual:          IL_002a:  starg.s    xs1
  ==
  
  ==
  Name: '.method assembly static bool  contains@1<a>(!!a e,'
  
  Expected:        IL_0030:  starg.s    e
  Actual:          IL_002c:  starg.s    e
  ==
  
  ==
  Name: '.method assembly static bool  contains@1<a>(!!a e,'
  
  Expected:        IL_0032:  br.s       IL_0000
  Actual:          IL_002e:  br.s       IL_0000
  ==
  
  \Expected:
  .method assembly static bool  contains@1<a>(!!a e,
                                                    class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> xs1) cil managed
        {
          .custom instance void [runtime]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = ( 01 00 00 00 )
  
          .maxstack  4
          .locals init (class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> V_0,
                   class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> V_1,
                   float64 V_2)
          IL_0000:  ldarg.1
          IL_0001:  call       instance class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>::get_TailOrNull()
          IL_0006:  brfalse.s  IL_000a
  
          IL_0008:  br.s       IL_000c
  
          IL_000a:  ldc.i4.0
          IL_000b:  ret
  
          IL_000c:  ldarg.1
          IL_000d:  stloc.0
          IL_000e:  ldloc.0
          IL_000f:  call       instance class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>::get_TailOrNull()
          IL_0014:  stloc.1
          IL_0015:  ldloc.0
          IL_0016:  call       instance !0 class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>::get_HeadOrDefault()
          IL_001b:  stloc.2
          IL_001c:  ldc.r8     (00 00 00 00 00 00 F8 FF)
          IL_0025:  ldloc.2
          IL_0026:  ceq
          IL_0028:  brfalse.s  IL_002c
  
          IL_002a:  ldc.i4.1
          IL_002b:  ret
  
          IL_002c:  ldarg.0
          IL_002d:  ldloc.1
          IL_002e:  starg.s    xs1
          IL_0030:  starg.s    e
          IL_0032:  br.s       IL_0000
        }
  
  
  
  Actual:
  .method assembly static bool  contains@1<a>(!!a e,
                                                class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> xs1) cil managed
    {
      .custom instance void [runtime]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = ( 01 00 00 00 )
  
      .maxstack  4
      .locals init (class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> V_0,
               class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> V_1,
               float64 V_2)
      IL_0000:  ldarg.1
      IL_0001:  call       instance class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>::get_TailOrNull()
      IL_0006:  brfalse.s  IL_000a
  
      IL_0008:  br.s       IL_000c
  
      IL_000a:  ldc.i4.0
      IL_000b:  ret
  
      IL_000c:  ldarg.1
      IL_000d:  stloc.0
      IL_000e:  ldloc.0
      IL_000f:  call       instance class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>::get_TailOrNull()
      IL_0014:  stloc.1
      IL_0015:  ldloc.0
      IL_0016:  call       instance !0 class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>::get_HeadOrDefault()
      IL_001b:  stloc.2
      IL_001c:  call       float64 [FSharp.Core]Microsoft.FSharp.Core.Operators::get_NaN()
      IL_0021:  ldloc.2
      IL_0022:  ceq
      IL_0024:  brfalse.s  IL_0028
  
      IL_0026:  ldc.i4.1
      IL_0027:  ret
  
      IL_0028:  ldarg.0
      IL_0029:  ldloc.1
      IL_002a:  starg.s    xs1
      IL_002c:  starg.s    e
      IL_002e:  br.s       IL_0000
    }
  
  
  Entire actual:
  
  
  
  
  
  .assembly extern runtime { }
  .assembly extern FSharp.Core { }
  .assembly assembly
  {
    .custom instance void [FSharp.Core]Microsoft.FSharp.Core.FSharpInterfaceDataVersionAttribute::.ctor(int32,
                                                                                                        int32,
                                                                                                        int32) = ( 01 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 )
    .hash algorithm 0x00008004
    .ver 0:0:0:0
  }
  .mresource public FSharpSignatureData.assembly
  {
  
  
  }
  .mresource public FSharpOptimizationData.assembly
  {
  
  
  }
  .module assembly.exe
  
  .imagebase {value}
  .file alignment 0x00000200
  .stackreserve 0x00100000
  .subsystem 0x0003
  .corflags 0x00000001
  
  
  
  
  
  .class public abstract auto ansi sealed Test
         extends [runtime]System.Object
  {
    .custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = ( 01 00 07 00 00 00 00 00 )
    .method public specialname static class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>
            get_data() cil managed
    {
  
      .maxstack  8
      IL_0000:  ldsfld     class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> '<StartupCode$assembly>'.$Test$fsx::data@2
      IL_0005:  ret
    }
  
    .method public specialname static bool
            get_found() cil managed
    {
  
      .maxstack  8
      IL_0000:  ldsfld     bool '<StartupCode$assembly>'.$Test$fsx::found@3
      IL_0005:  ret
    }
  
    .method assembly specialname static class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>
            get_source@1() cil managed
    {
  
      .maxstack  8
      IL_0000:  ldsfld     class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> '<StartupCode$assembly>'.$Test$fsx::source@1
      IL_0005:  ret
    }
  
    .method assembly static bool  contains@1<a>(!!a e,
                                                class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> xs1) cil managed
    {
      .custom instance void [runtime]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = ( 01 00 00 00 )
  
      .maxstack  4
      .locals init (class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> V_0,
               class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> V_1,
               float64 V_2)
      IL_0000:  ldarg.1
      IL_0001:  call       instance class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>::get_TailOrNull()
      IL_0006:  brfalse.s  IL_000a
  
      IL_0008:  br.s       IL_000c
  
      IL_000a:  ldc.i4.0
      IL_000b:  ret
  
      IL_000c:  ldarg.1
      IL_000d:  stloc.0
      IL_000e:  ldloc.0
      IL_000f:  call       instance class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>::get_TailOrNull()
      IL_0014:  stloc.1
      IL_0015:  ldloc.0
      IL_0016:  call       instance !0 class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>::get_HeadOrDefault()
      IL_001b:  stloc.2
      IL_001c:  call       float64 [FSharp.Core]Microsoft.FSharp.Core.Operators::get_NaN()
      IL_0021:  ldloc.2
      IL_0022:  ceq
      IL_0024:  brfalse.s  IL_0028
  
      IL_0026:  ldc.i4.1
      IL_0027:  ret
  
      IL_0028:  ldarg.0
      IL_0029:  ldloc.1
      IL_002a:  starg.s    xs1
      IL_002c:  starg.s    e
      IL_002e:  br.s       IL_0000
    }
  
    .property class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>
            data()
    {
      .custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = ( 01 00 09 00 00 00 00 00 )
      .get class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> Test::get_data()
    }
    .property bool found()
    {
      .custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = ( 01 00 09 00 00 00 00 00 )
      .get bool Test::get_found()
    }
    .property class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>
            source@1()
    {
      .custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = ( 01 00 09 00 00 00 00 00 )
      .get class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> Test::get_source@1()
    }
  }
  
  .class private abstract auto ansi sealed '<StartupCode$assembly>'.$Test$fsx
         extends [runtime]System.Object
  {
    .field static assembly class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> data@2
    .custom instance void [runtime]System.Diagnostics.DebuggerBrowsableAttribute::.ctor(valuetype [runtime]System.Diagnostics.DebuggerBrowsableState) = ( 01 00 00 00 00 00 00 00 )
    .field static assembly bool found@3
    .custom instance void [runtime]System.Diagnostics.DebuggerBrowsableAttribute::.ctor(valuetype [runtime]System.Diagnostics.DebuggerBrowsableState) = ( 01 00 00 00 00 00 00 00 )
    .field static assembly class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> source@1
    .custom instance void [runtime]System.Diagnostics.DebuggerBrowsableAttribute::.ctor(valuetype [runtime]System.Diagnostics.DebuggerBrowsableState) = ( 01 00 00 00 00 00 00 00 )
    .field static assembly int32 init@
    .custom instance void [runtime]System.Diagnostics.DebuggerBrowsableAttribute::.ctor(valuetype [runtime]System.Diagnostics.DebuggerBrowsableState) = ( 01 00 00 00 00 00 00 00 )
    .custom instance void [runtime]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = ( 01 00 00 00 )
    .custom instance void [runtime]System.Diagnostics.DebuggerNonUserCodeAttribute::.ctor() = ( 01 00 00 00 )
    .method public static void  main@() cil managed
    {
      .entrypoint
  
      .maxstack  6
      IL_0000:  call       float32 [FSharp.Core]Microsoft.FSharp.Core.Operators::get_NaNSingle()
      IL_0005:  conv.r8
      IL_0006:  ldc.r8     5.
      IL_000f:  call       float64 [FSharp.Core]Microsoft.FSharp.Core.Operators::get_Infinity()
      IL_0014:  call       class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>::get_Empty()
      IL_0019:  call       class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>::Cons(!0,
                                                                                                                                                                        class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0>)
      IL_001e:  call       class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>::Cons(!0,
                                                                                                                                                                        class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0>)
      IL_0023:  call       class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>::Cons(!0,
                                                                                                                                                                        class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0>)
      IL_0028:  stsfld     class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> '<StartupCode$assembly>'.$Test$fsx::data@2
      IL_002d:  call       class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> Test::get_data()
      IL_0032:  stsfld     class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> '<StartupCode$assembly>'.$Test$fsx::source@1
      IL_0037:  call       float64 [FSharp.Core]Microsoft.FSharp.Core.Operators::get_NaN()
      IL_003c:  call       class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64> Test::get_source@1()
      IL_0041:  call       bool Test::contains@1<float64>(!!0,
                                                          class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<float64>)
      IL_0046:  stsfld     bool '<StartupCode$assembly>'.$Test$fsx::found@3
      IL_004b:  ret
    }
  
  }
  
  
  
  
  
  
  
    Stack Trace:
       at NUnit.Framework.Assert.ReportFailure(String message)
     at NUnit.Framework.Assert.Fail(String message, Object[] args)
     at NUnit.Framework.Assert.Fail(String message)
     at FSharp.Test.ILChecker.checkILAux(IEnumerable`1 ildasmArgs, String dllFilePath, FSharpList`1 expectedIL) in C:\source\fsharp\tests\FSharp.Test.Utilities\ILChecker.fs:line 157
     at FSharp.Test.ILChecker.checkIL(String dllFilePath, FSharpList`1 expectedIL) in C:\source\fsharp\tests\FSharp.Test.Utilities\ILChecker.fs:line 165
     at FSharp.Test.Compiler.verifyIL@1118.Invoke(String dllFilePath, FSharpList`1 expectedIL)
     at FSharp.Test.Compiler.doILCheck[a](FSharpFunc`2 func, FSharpList`1 il, CompilationResult result) in C:\source\fsharp\tests\FSharp.Test.Utilities\Compiler.fs:line 1115
     at FSharp.Test.Compiler.verifyIL@1118-1.Invoke(FSharpList`1 il, CompilationResult result)
     at EmittedIL.Inlining.List contains inlining() in C:\source\fsharp\tests\FSharp.Compiler.ComponentTests\EmittedIL\Inlining\Inlining.fs:line 47
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
     at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
  ```

    </p>
  </details>
* **Conformance.BasicGrammarElements.StaticLet.Static let union - order of execution(compilation: UnionOrderOfExecution.fs)**
  `withStdOutContains` with multiline string `""" """`
  Test outputs `\r\n` on Windows due to `printfn` -> `TextWriter.WriteLine` -> `Environment.NewLine`.
  This doesn't go well with `git config core.autocrlf` `input` which checkouts souce with `\n` only
 
  <details><summary>Details</summary>
  <p>

  ```
      Failed Conformance.BasicGrammarElements.StaticLet.Static let union - order of execution(compilation: UnionOrderOfExecution.fs) [333 ms]
    Error Message:
     System.Exception :
  The following substring:
      "init type U
  side effect in let binding case2cachedVal
  Before accessing type
  side effect in member Singleton
  calling print Case2 42
  side effect in member Singleton
  calling print Case2 42"
  was not found in the "STDOUT"
  Output:
      "init type U
  side effect in let binding case2cachedVal
  Before accessing type
  side effect in member Singleton
  calling print Case2 42
  side effect in member Singleton
  calling print Case2 42
  "
    Stack Trace:
  ```

  </p>
  </details>

  Same problem with:
```
1. Conformance.BasicGrammarElements.StaticLet.Static let - recursive record definitions calling each other(compilation: RecursiveRecords.fs)
2. Conformance.BasicGrammarElements.StaticLet.Static let in empty generic type(compilation: SimpleEmptyGenericType.fs)
3. Conformance.BasicGrammarElements.StaticLet.Static let - union showcase(compilation: UnionShowCase.fs)
4. Conformance.BasicGrammarElements.StaticLet.Static let union - executes per generic struct typar(compilation: StaticLetInGenericUnion.fs)
5. Conformance.BasicGrammarElements.StaticLet.Static let record - executes per generic typar(compilation: StaticLetInGenericRecords.fs)
6. Conformance.BasicGrammarElements.StaticLet.Static let record - order of execution(compilation: RecordOrderOfExecution.fs)
7. Conformance.BasicGrammarElements.StaticLet.Static let - recursive DU definitions calling each other(compilation: RecursiveDUs.fs)
8. Conformance.BasicGrammarElements.StaticLet.Static let - record showcase(compilation: RecordShowCase.fs)
9. Conformance.BasicGrammarElements.StaticLet.Static let in DU in penultimate file
10. Conformance.BasicGrammarElements.StaticLet.Static let in empty type(compilation: SimpleEmptyType.fs)
```

**Related information**

Provide any related information (optional):

```
Test Run Failed.
Total tests: 3116
     Passed: 2908
     Failed: 12
    Skipped: 196
 Total time: 25,8700 Minutes
```
```
dotnet --info
.NET SDK:
 Version:   8.0.100-rc.1.23463.5
 Commit:    e7f4de8816

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.1.23463.5\

Host:
  Version:      8.0.0-rc.1.23419.4
  Architecture: x64
  Commit:       92959931a3
  RID:          win-x64
```

**Comment by vzarytovskii** [comment]
Tests are needed to be running in Release mode, since we're actually interested in checking release codegen.

**Comment by vzarytovskii** [comment]
Tests are needed to be running in Release mode, since we're actually interested in checking release codegen.

**Comment by vzarytovskii** [comment]
The multiline check needs to be improved, I'm going to close it, it probably can be fixed/improved together with PR when you're adding tests in PR probably?

**Comment by OwnageIsMagic** [comment]
@vzarytovskii so maybe skip it in debug build? It's not very pleasant onbording when fresh checkout spams with warns https://github.com/fsharp/fsharp/issues/493 https://github.com/dotnet/fsharp/issues/9472 and tests are failing. [DEVGUIDE.md](https://github.com/dotnet/fsharp/blob/main/DEVGUIDE.md#performance-and-debugging) says
> Use the `Debug` configuration to test your changes locally. It is the default. Do not use the `Release` configuration! Local development and testing of Visual Studio tooling is not designed for the Release configuration.

**Comment by vzarytovskii** [comment]
> @vzarytovskii so maybe skip it in debug build? It's not very pleasant onbording when fresh checkout spams with warns https://github.com/fsharp/fsharp/issues/493 https://github.com/dotnet/fsharp/issues/9472 and tests are failing. [DEVGUIDE.md](https://github.com/dotnet/fsharp/blob/main/DEVGUIDE.md#performance-and-debugging) says
> 
> > Use the `Debug` configuration to test your changes locally. It is the default. Do not use the `Release` configuration! Local development and testing of Visual Studio tooling is not designed for the Release configuration.

Can't skip, since we still want to debug them, as in step through, in debug configuration, and run in VS in release. I guess devguide says more about which compiler to run locally and/or attach to.

Might need clarification about which test configuration should be used.
