### ISSUE TITLE
ERROR: First Error Message: Error MSB6006. "dotnet.exe" exited with code -532462766. 

### ISSUE THREAD

**Issue by derigel23** [dotnet/fsharp#16272]
I've had no clue what's the problem is until I found this in event viewer.
```
Application: dotnet.exe
CoreCLR Version: 8.0.23.47906
.NET Version: 8.0.0-rc.2.23479.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at FSharp.Compiler.Driver.main1(CompilationThreadToken ctok, String[] argv, LegacyReferenceResolver legacyReferenceResolver, Boolean bannerAlreadyPrinted, ReduceMemoryFlag reduceMemoryUsage, CopyFSharpCoreFlag defaultCopyFSharpCore, Exiter exiter, IDiagnosticsLoggerProvider diagnosticsLoggerProvider, DisposablesTracker disposables) in C:\MSBFU\visualfsharp\src\Compiler\Driver\fsc.fs:line 490
   at FSharp.Compiler.Driver.CompileFromCommandLineArguments(CompilationThreadToken ctok, String[] argv, LegacyReferenceResolver legacyReferenceResolver, Boolean bannerAlreadyPrinted, ReduceMemoryFlag reduceMemoryUsage, CopyFSharpCoreFlag defaultCopyFSharpCore, Exiter exiter, IDiagnosticsLoggerProvider loggerProvider, FSharpOption`1 tcImportsCapture, FSharpOption`1 dynamicAssemblyCreator) in C:\MSBFU\visualfsharp\src\Compiler\Driver\fsc.fs:line 1197
   at FSharp.Compiler.CommandLineMain.main(String[] argv) in C:\MSBFU\visualfsharp\src\fsc\fscmain.fs:line 84
   at FSharp.Compiler.DiagnosticsLogger.DiagnosticsLoggerExtensions.ReraiseIfWatsonable(Exception exn) in C:\MSBFU\visualfsharp\src\Compiler\Facilities\DiagnosticsLogger.fs:line 419
   at FSharp.Compiler.DiagnosticsLogger.DiagnosticsLoggerExtensions.DiagnosticsLogger.ErrorRecovery(DiagnosticsLogger x, Exception exn, Range m) in C:\MSBFU\visualfsharp\src\Compiler\Facilities\DiagnosticsLogger.fs:line 470
   at FSharp.Compiler.DiagnosticsLogger.errorRecovery(Exception exn, Range m) in C:\MSBFU\visualfsharp\src\Compiler\Facilities\DiagnosticsLogger.fs:line 571
   at FSharp.Compiler.CommandLineMain.main(String[] argv) in C:\MSBFU\visualfsharp\src\fsc\fscmain.fs:line 101
```
While it's dotnet problem FSC should be less error-prone and do not crash randomly.
But catch exceptions at the highest level and report them clearly.

**Comment by derigel23** [comment]
FYI, problem with dotnet8 is caused by setting `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT ` to true.
But it's not related to this ticket directly. It's just example of system failure which FSC hides and makes hard to understand.
