### ISSUE TITLE
Exception at IncrementalBuild.fs Line 813: The input array was empty. (Parameter 'array')

### ISSUE THREAD

**Issue by jcoder58** [dotnet/fsharp#16312]
Please provide a succinct description of the issue.

Called ParseAndCheckProject with small fs project and got exception in title 

**Repro steps**

See attached zip file.

> cd Test
> dotnet run ..\Game\Game.fsproj

**Expected behavior**

No exception.

**Actual behavior**

```
> dotnet run ..\Game\Game.fsproj
Arguments passed to function : [|"..\Game\Game.fsproj"|] C:\UnrealEngine\Test\Test\Test
Unhandled exception. System.AggregateException: One or more errors occurred. (The input array was empty. (Parameter 'array'))
 ---> System.ArgumentException: The input array was empty. (Parameter 'array')
   at FSharp.Compiler.CodeAnalysis.IncrementalBuilderHelpers.FinalizeTypeCheckTask@752-10.Invoke(FSharpOption`1[] latestImplFiles) in D:\a\_work\1\s\src\Compiler\Service\IncrementalBuild.fs:line 758
   at FSharp.Compiler.BuildGraph.Bind@61-1.Invoke(T x) in D:\a\_work\1\s\src\Compiler\Facilities\BuildGraph.fs:line 62
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 528
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 454
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1140
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1167
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1511
   at Program.compile(String projPath) in C:\UnrealEngine\Test\Test\Test\Program.fs:line 10
   at Program.main(String[] args) in C:\UnrealEngine\Test\Test\Test\Program.fs:line 19
```

**Known workarounds**

FSharp.Compiler.Service 42.7.101 runs to completion.

**Related information**

Provide any related information (optional):

Windows 11
.NET 8.0

[Test.zip](https://github.com/dotnet/fsharp/files/13418759/Test.zip)

**Comment by majocha** [comment]
I think you need to pass the list of files in args:
```F#
    let projectOptions = checker.GetProjectOptionsFromCommandLineArgs(
        projPath, [| "Library.fs" |])
```



As for the exception, this does not look right.
There is a silent assumption that we have at least one source file, when creating a builder. Obviously this is not covered by tests.
I don't know what is best to do in such case. Maybe we should return a diagnostic error?

**Comment by jcoder58** [comment]
> I think you need to pass the list of files in args:

Why is that?  I assumed that if a project file was give as an argument, the file would be used as a source for all the files and references.
