### ISSUE TITLE
AccessViolationException when running IncrementalBuild (from FsAutocomplete in Ionide in Dev Containers)

### ISSUE THREAD

**Issue by Martin521** [dotnet/fsharp#16333]
**Repro steps**

Open this repository in a dev container in VS Code.
Work on the compiler for a while.

After some time, I inevitably see a crash of FsAutocomplete with this stack trace:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at System.IO.UnmanagedMemoryStream.WriteCore(System.ReadOnlySpan`1<Byte>)
   at System.Reflection.Metadata.BlobBuilder.WriteContentTo(System.IO.Stream)
   at FSharp.Compiler.CodeAnalysis.ItemKeyStoreBuilder.TryBuildAndReset()
   at <StartupCode$FSharp-Compiler-Service>.$IncrementalBuild+clo@334-470.Invoke(System.Tuple`5<FSharp.Compiler.CodeAnalysis.TcInfo,TcResultsSinkImpl,Microsoft.FSharp.Core.FSharpOption`1<CheckedImplFile>,System.String,System.Tuple`2<PhasedDiagnostic,FSharp.Compiler.Diagnostics.FSharpDiagnosticSeverity>[]>)
   at FSharp.Compiler.BuildGraph+Bind@61-1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(System.__Canon)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.FSharp.Control.AsyncActivation`1<System.__Canon>, System.__Canon, Microsoft.FSharp.Core.FSharpFunc`2<System.__Canon,Microsoft.FSharp.Control.FSharpAsync`1<System.__Canon>>)
   at Microsoft.FSharp.Control.Trampoline.Execute(Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.AsyncReturn>)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
...
```

**Related information**

Windows11/WSL2 with Docker, VS Code with DevContainers, current dotnet/fsharp repository

**Comment by vzarytovskii** [comment]
It happens with memory mapped files, I'm pretty sure it's related to how WSL works. Nothing we can really do about it.

**Comment by vzarytovskii** [comment]
Also, probably belongs to runtime repo, not fsharp.

**Comment by Martin521** [comment]
It seems I had too much trust in the runtime when I posted it here ;-)
Thanks for the link, I will see if I can find some WSL or Docker settings that avoid this.
If not, then dev container is not really as great for working on the compiler as I thought.

**Comment by Martin521** [comment]
It turns out I had given too little memory to WSL. 12GB is too little.
With this .wslconfig
```
[wsl2]
memory=28GB
processors=8
kernelCommandLine = "sysctl.vm.overcommit_memory=2" "sysctl.vm.overcommit_ratio=100"
```
I have still seen the crash, but much less often. It seems workable now.
I am not sure if the overcommit configuration really makes a difference (because I still see 260GB VIRT for the dotnet process), but at some point that was my impression.
The main requirement certainly is sufficient memory.

**Comment by vzarytovskii** [comment]
> It turns out I had given too little memory to WSL. 12GB is too little.
> 
> With this .wslconfig
> 
> ```
> 
> [wsl2]
> 
> memory=28GB
> 
> processors=8
> 
> kernelCommandLine = "sysctl.vm.overcommit_memory=2" "sysctl.vm.overcommit_ratio=100"
> 
> ```
> 
> I have still seen the crash, but much less often. It seems workable now.
> 
> I am not sure if the overcommit configuration really makes a difference (because I still see 260GB VIRT for the dotnet process), but at some point that was my impression.
> 
> The main requirement certainly is sufficient memory.
> 
> 

I think one of the issues is also that Linux allocates mmaped memory in /dev, which by default uses like 50% of memory only.

Remapping it with more memory might be the way.
