### ISSUE TITLE
An exception in the ChangePrefixNegationToInfixSubstraction code fix

### ISSUE THREAD

**Issue by psfinaki** [dotnet/fsharp#16356]
This code throws:
```fsharp
type MyType = { Value: int }

let test = { Value = 42 }x
```

The stack trace:
```fsharp
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.VisualStudio.Text.Implementation.StringRebuilderForString.get_Item(Int32 index)
   at async StartupCode$FSharp-Editor(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.CodeFixExtensions.CodeFixContext-RegisterFsharpFix@93(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

This happens because the code above happens to produce FS0003 (This value is not a function) whereas the code fix searches for the `-` sign in the code and fails to find one here.

**Comment by brianrourkeboll** [comment]
Was this fixed by #17448?

**Comment by psfinaki** [comment]
I don't think so, repros in main 🤔

**Comment by brianrourkeboll** [comment]
> I don't think so, repros in main 🤔

Hmm, it doesn't seem to repro for me.

**Comment by psfinaki** [comment]
Right, actually you're correct, I had old old main in my branch 🤦 
This seems to be fixed then, thanks for pointing out, closing the ticket!
