### ISSUE TITLE
TransparentCompiler: Checking `FSharp.Compiler.Service.sln` causes an exception

### ISSUE THREAD

**Issue by safesparrow** [dotnet/fsharp#16730]
Using FCS in a console app to check the `FSharp.Compiler.Service.sln` causes an internal exception.

**Repro steps**

Run the following script to check out & run the `fsharp_scripts` app:
```powershell
# Checkout https://github.com/safesparrow/fsharp_scripts/tree/75f44f3cd66670b977b9c4eab2299c0f626ac171
git clone https://github.com/safesparrow/fsharp_scripts
cd fsharp_scripts
git checkout 75f44f3cd66670b977b9c4eab2299c0f626ac171
cd Scripts.IDETests

# Run the IDE test - checkout this sample: https://github.com/safesparrow/fsharp_scripts/blob/1dcaf91d61d52a4b4b9e7ff292d98999cd53b517/More.fs#L57-L65 and run with TC enabled
dotnet run --sample FCS --tcmodes ON
```

**Expected behavior**

Checker does not crash.

**Actual behavior**

Checker crashes with:
```
[13:58:10 INF]  : -                    | FileChecked C:\projekty\fsharp\fsharp_scripts\.cache\dotnet__fsharp\9ae94bb9\_\src\FSharp.Core\fslib-extra-pervasives.fs
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (The input list was empty. (Parameter 'list'))))))
 ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (The input list was empty. (Parameter 'list')))))
 ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (The input list was empty. (Parameter 'list'))))
 ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (The input list was empty. (Parameter 'list')))
 ---> System.AggregateException: One or more errors occurred. (The input list was empty. (Parameter 'list'))
 ---> System.ArgumentException: The input list was empty. (Parameter 'list')
   at Microsoft.FSharp.Collections.ListModule.Reduce[T](FSharpFunc`2 reduction, FSharpList`1 list) in D:\a\_work\1\s\src\FSharp.Core\list.fs:line 306
   at FSharp.Compiler.GraphChecking.TrieMapping.mkTrieNodeFor(FileInProject file) in D:\a\_work\1\s\src\Compiler\Driver\GraphChecking\TrieMapping.fs:line 226
   at FSharp.Compiler.GraphChecking.TrieMapping.mkTrie@292.Invoke(FileInProject file)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map@2063-2.Invoke(Int32 i) in D:\a\_work\1\s\src\FSharp.Core\array.fs:line 2063
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map[T,TResult](FSharpFunc`2 mapping, T[] array) in D:\a\_work\1\s\src\FSharp.Core\array.fs:line 2063
   at FSharp.Compiler.GraphChecking.TrieMapping.mkTrie(FileInProject[] files) in D:\a\_work\1\s\src\Compiler\Driver\GraphChecking\TrieMapping.fs:line 290
   at FSharp.Compiler.GraphChecking.DependencyResolution.mkGraph(FilePairMap filePairs, FileInProject[] files) in D:\a\_work\1\s\src\Compiler\Driver\GraphChecking\DependencyResolution.fs:line 195
   at <StartupCode$FSharp-Compiler-Service>.$TransparentCompiler.clo@1051-609.Invoke(IDisposable _arg29) in D:\a\_work\1\s\src\Compiler\Service\TransparentCompiler.fs:line 1059
   at FSharp.Compiler.BuildGraph.Using@114-6.Invoke(IDisposable _arg6) in D:\a\_work\1\s\src\Compiler\Facilities\BuildGraph.fs:line 114
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 510
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
   --- End of inner exception stack trace ---
   at <StartupCode$FSharp-Compiler-Service>.$AsyncMemoize.Get@498-12.Invoke(Exception _arg15) in D:\a\_work\1\s\src\Compiler\Facilities\AsyncMemoize.fs:line 531
   at FSharp.Compiler.BuildGraph.TryWith@70-2.Invoke(Exception x)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt, FSharpFunc`2 filterFunction, ExceptionDispatchInfo edi) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 547
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
   --- End of inner exception stack trace ---
   at <StartupCode$FSharp-Compiler-Service>.$AsyncMemoize.Get@498-12.Invoke(Exception _arg15) in D:\a\_work\1\s\src\Compiler\Facilities\AsyncMemoize.fs:line 531
   at FSharp.Compiler.BuildGraph.TryWith@70-2.Invoke(Exception x)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt, FSharpFunc`2 filterFunction, ExceptionDispatchInfo edi) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 547
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Scripts.IDE.Pipe #1 stage #1 at line 120@122-1.Invoke(Unit unitVar) in C:\projekty\fsharp\fsharp_scripts\IDE.fs:line 122
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 510
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Scripts.IDE.IDE.CheckAllProjectsInParallel() in C:\projekty\fsharp\fsharp_scripts\IDE.fs:line 129
   at Scripts.Sample.Program.testIDE(Sample spec, Boolean transparentCompiler) in C:\projekty\fsharp\fsharp_scripts\Scripts.Sample\Program.fs:line 46
   at Scripts.Sample.Program.main(String[] argv) in C:\projekty\fsharp\fsharp_scripts\Scripts.Sample\Program.fs:line 94
```

**Related information**

Same happens for the `FSharp.Data` solution that you can test with:
```
dotnet run --sample FSharpData --tcmodes On --parallelreferenceresolution false
```

and for the `Paket` solution that you can test with:
```
dotnet run --sample Paket --tcmodes On --parallelreferenceresolution false
```
The error for `Paket` happens when checking the `Paket.Bootstrapper` project:
```
[22:22:22 INF]  : -                    | FileParsed  C:\projekty\fsharp\fsharp_scripts\.cache\fsprojects__Paket\4954f9f2\_\src\Paket.Bootstrapper\SemVer.cs
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (The input list was empty. (Parameter 'list')) (The input list was empty. (Parameter 'list')) (The input list was empty. (Parameter 'list')) (The input list was empty. (Parameter 'list')) (The input list was empty. (Parameter 'list')) (The input list was empty. (Parameter 'list'))))))
```

Running the same with `--tcmodes Off`, ie. no Transparent Compiler, does not crash.

Provide any related information (optional):

* FCS version `43.8.300-preview.24115.2`, published on 2024-02-16 (latest available on NuGet)
* Operating system: Windows 11
* .NET SDK 8.0.100

**Comment by safesparrow** [comment]
Hmm, this looks to be entirely my fault. I was using ProjInfo to generate `FSharpOptions` for all projects in sample solutions, but didn't take into account that some of those projects might be C# projects.

So the exceptions were actually coming from FCS attempting to check a C# project 🙃 

Apologies, will close this now.

**Comment by vzarytovskii** [comment]
> Hmm, this looks to be entirely my fault. I was using ProjInfo to generate `FSharpOptions` for all projects in sample solutions, but didn't take into account that some of those projects might be C# projects.
> 
> So the exceptions were actually coming from FCS attempting to check a C# project 🙃
> 
> Apologies, will close this now.

It'll still probably be a good idea to guard against empty list in the `FSharp.Compiler.GraphChecking.TrieMapping.mkTrieNodeFor` and print a more user-friendly message when throwing an exception.
