### ISSUE TITLE
AddReturnType refactoring occasionally throws

### ISSUE THREAD

**Issue by psfinaki** [dotnet/fsharp#16844]
I cannot come up with a definitive repo but this _sometimes_ happens when I just copy a file in the solution explorer.

Here is the stack trace:
```fsharp
System.Exception : The file 'C:\code\fsharp3\tests\benchmarks\FCSBenchmarks\CompilerServiceBenchmarks\GraphTypeCheckingBenchmarks - Copy.fs' was not part of the project. Did you call InvalidateConfiguration when the list of files in the project changed?
   at FSharp.Compiler.CodeAnalysis.IncrementalBuilder.GetSlotOfFileName(String fileName)
   at <StartupCode$FSharp-Compiler-Service>.$BackgroundCompiler.ParseAndCheckFileInProject@919-3.Invoke(FSharpOption`1 cachedResults)
   at FSharp.Compiler.BuildGraph.Bind@63-1.Invoke(T x)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt,b result1,FSharpFunc`2 userCode)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.CheckerExtensions.FSharpChecker-ParseAndCheckDocumentWithPossibleStaleResults@388-3(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.CheckerExtensions.FSharpChecker-ParseAndCheckDocumentWithPossibleStaleResults@378(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.CheckerExtensions.FSharpChecker-ParseAndCheckDocument@449(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.FSharp.Editor.WorkspaceExtensions.Document-GetFSharpParseAndCheckResultsAsync@539(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StartupCode$FSharp-Editor(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<>c__DisplayClass12_0.<GetRefactoringFromProviderAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by kerams** [comment]
Every time I create a new fs file (Add above - Add new item).

**Comment by vzarytovskii** [comment]
This likely happens because project system doesn't send us new command line options fast enough and we ask for tc results for file which is not in the project yet.

**Comment by psfinaki** [comment]
> Every time I create a new fs file (Add above - Add new item).

Hah indeed, as easy as that, thanks. 

The way I usually add files to the project is that I copypaste an existing file (I don't know why actually) - and that doesn't throw, or at least doesn't throw in the repeatable fashion.

**Comment by BentTranberg** [comment]
This happens often in my VS 2022, and it started a long time ago. It causes an information bar to appear in VS. Here's a screenshot of it. I clicked "Show Stack Trace" in that information bar, but you see the bar above the stack dialog.

<img width="1347" height="716" alt="Image" src="https://github.com/user-attachments/assets/50a16764-a888-41b9-9131-08e4e19fde90" />

So far I've been suspecting it might have something to do with me using the VisualSVN extension in VS, but looking at the stack trace I rather suspect it's the F# compiler alone that causes it. VisualSVN has hardly ever caused any trouble since I started using it in 2007. Could be caused by a mix of those two of course. But I'll leave further speculations to you compiler experts.

It doesn't bother me much. I just click Enable and continue work. Maybe something stops working, but if so I haven't noticed what.

**Comment by T-Gro** [comment]
It can be if the VisualSVN modifies files on disk (e.g. a project file) faster then VS sends new project arguments to the F# extension.
When it comes to the refactoring service, a solution here can likely be making it more robust and delaying to a no-op in that situation (i.e. when refactoring provider asks for refactorings about a file that is not yet known to the extension, yield empty instead of throwing)
