### ISSUE TITLE
VS: crash or hang when accessing F# Text Editor options

### ISSUE THREAD

**Issue by majocha** [dotnet/fsharp#16965]
Current `main` installed on 17.10 preview 2:

**Repro steps**

Open settings, go to Text Editor -> F# -> Advanced ( or any other F# page).

VS either hangs or crashes and restarts.

Attempting to debug this in experimental instance I get:

> Managed Debugging Assistant 'FatalExecutionEngineError' : 'The runtime has encountered a fatal error. The address of the error was at 0x423bffe8, on thread 0x763c. The error code is 0x80131623. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.'

**Comment by brianrourkeboll** [comment]
I've seen this as well.

**Comment by majocha** [comment]
Possibly it's some VS platform / WPF bug.
It happens around setting DataContext for the view, the options window just breaks:
![image](https://github.com/dotnet/fsharp/assets/1760221/aaec4685-d6c4-43f6-b664-bd5c932e6e9e)

**Comment by majocha** [comment]
Original version released with 17.10 preview  i.e:
Visual F# Tools   17.10.0-beta.24127.3+b57dee7cec971021547a7b8a36a46d7271fea99e
works fine.

**Comment by vzarytovskii** [comment]
I bet it's translation.

**Comment by vzarytovskii** [comment]
Ok, maybe not
```csharp
Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "Microsoft.VisualStudio.FSharp.Editor.SettingsStore+ISettingsStore" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.VisualStudio.FSharp.Editor.OptionsUIHelpers.AbstractOptionPage`1.OnActivate(CancelEventArgs _arg1) in C:\Users\vlza\code\fsharp\vsintegration\src\FSharp.Editor\Options\UIHelpers.fs:line 37
   at Microsoft.VisualStudio.Shell.DialogPage.DialogSubclass.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at Microsoft.Internal.VisualStudio.Shell.Interop.IVsToolsOptionsPrivate2.ShowToolsOptions(Guid selectedPageId)
   at Microsoft.VisualStudio.Services.UnifiedSettings.VsCommands.ToolsOptionsCommand.<>c__DisplayClass6_0.<<Execute>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.VsTaskLibraryHelper.<>c.<<FileAndForget>b__35_0>d.MoveNext()
```

**Comment by majocha** [comment]
@vzarytovskii this call stack looks helpful! I got it to work again at least in debug. I'll post what I got soon.

**Comment by majocha** [comment]
Nah, now I just can't repro this at all, on `main` without any changes. It just comes and goes.

**Comment by majocha** [comment]
@vzarytovskii I can't repro in debug at all now, but I'll test your fix on my VS installation in a moment.

**Comment by vzarytovskii** [comment]
> @vzarytovskii I can't repro in debug at all now, but I'll test your fix on my VS installation in a moment.

I couldn't reproduce in debug either

**Comment by majocha** [comment]
Works!
