### ISSUE TITLE
F# compiler is generating invalid IL

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/fsharp#18702]
_From @NickDarvey on Wed, 21 Jun 2023 11:28:51 GMT_

### Steps to Reproduce

1. Download `FsToolkitiOSApp.zip` (attached)
2. Run
    ```
    dotnet build -c Release -t:Run -f net7.0-ios -p:RuntimeIdentifier=ios-arm64 -p:_DeviceName=1234 -bl
    ``` 

### Expected Behavior

Release build completes.

### Actual Behavior

```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7067/targets/Xamarin.Shared.Sdk.targets(765,3): ILStrip failed for obj/Release/net7.0-ios/ios-arm64/linked/FsToolkit.ErrorHandling.dll: Must be of type CilStrip.Mono.Cecil.TypeReference [/FsToolkitiOSApp.fsproj]


System.ArgumentException: Must be of type CilStrip.Mono.Cecil.TypeReference
   at CilStrip.Mono.Cecil.GenericArgumentCollection.OnValidate(Object o)
   at System.Collections.CollectionBase.System.Collections.IList.Add(Object value)
   at CilStrip.Mono.Cecil.GenericArgumentCollection.Add(TypeReference value)
   at CilStrip.Mono.Cecil.ReflectionReader.GetTypeRefFromSig(SigType t, GenericContext context)
   at CilStrip.Mono.Cecil.ReflectionReader.GetGenericArg(GenericArg arg, GenericContext context)
   at CilStrip.Mono.Cecil.ReflectionReader.GetTypeRefFromSig(SigType t, GenericContext context)
   at CilStrip.Mono.Cecil.ReflectionReader.CompleteParameter(ParameterDefinition parameter, Param signature, GenericContext context)
   at CilStrip.Mono.Cecil.ReflectionReader.BuildParameterDefinition(String name, Int32 sequence, ParameterAttributes attrs, Param psig, GenericContext context)
   at CilStrip.Mono.Cecil.ReflectionReader.CompleteMethods()
   at CilStrip.Mono.Cecil.ReflectionReader.VisitTypeDefinitionCollection(TypeDefinitionCollection types)
   at CilStrip.Mono.Cecil.AggressiveReflectionReader.VisitTypeDefinitionCollection(TypeDefinitionCollection types)
   at CilStrip.Mono.Cecil.ReflectionReader.VisitModuleDefinition(ModuleDefinition mod)
   at CilStrip.Mono.Cecil.StructureReader.TerminateAssemblyDefinition(AssemblyDefinition asm)
   at CilStrip.Mono.Cecil.AssemblyDefinition.Accept(IReflectionStructureVisitor visitor)
   at CilStrip.Mono.Cecil.AssemblyFactory.GetAssembly(ImageReader irv, Boolean manifestOnly)
   at CilStrip.Mono.Cecil.AssemblyFactory.GetAssembly(ImageReader reader)
   at CilStrip.Mono.Cecil.AssemblyFactory.GetAssembly(String file)
   at ILStrip.StripAssembly(ITaskItem assemblyItem)
   
```

### Environment

<details>
<summary>Version information</summary>

```
dotnet  7.0.304
dotnet workload maui-ios 7.0.86/7.0.100
```

</details>

### Build Logs and Example Project

[FsToolkitiOSApp.zip](https://github.com/xamarin/xamarin-macios/files/11816963/FsToolkitiOSApp.zip)

### Workaround

Disabling IL stripping, as described in https://github.com/xamarin/xamarin-macios/issues/14841#issue-1218995218, works.

Is there a way to _only_ disable it for this asssembly?

_Copied from original issue xamarin/xamarin-macios#18485_

**Comment by MichalStrehovsky** [comment]
`class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc2<!!'value'&, bool>>` is invalid IL. Byrefs cannot be generic type arguments.

This code does not work at runtime. ILStrip is free to crash on assemblies that don't conform to the file format.

I don't know nearly enough F# to reach this at runtime but a small C# test app that references the FsToolkit.ErrorHandling nuget (with no trimming or ILStrip whatsoever):

```csharp
var t = Type.GetType("FsToolkit.ErrorHandling.ValueOption, FsToolkit.ErrorHandling");
Console.WriteLine(t.GetMethod("tryParse$W"));
```

Will crash with:

```
Unhandled exception. System.TypeLoadException: The generic type 'Microsoft.FSharp.Core.FSharpFunc`2' was used with an invalid instantiation in assembly 'FSharp.Core, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.<get_Signature>g__LazyCreateSignature|25_0()
   at System.Reflection.RuntimeMethodInfo.ToString()
   at System.IO.TextWriter.WriteLine(Object value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(Object value)
   at System.Console.WriteLine(Object value)
   at Program.<Main>$(String[] args) in C:\Users\Michal\source\repos\Repro\Repro\Program.cs:line 2
```

**Comment by MichalStrehovsky** [comment]
Hmm, looks like I don't have sufficient rights to move this to the dotnet/fsharp repo. @T-Gro do you have sufficient rights to move this? This is an F# compiler bug (and maybe language bug if this is allowed?). The details at https://github.com/dotnet/fsharp/issues/18702, problematic code at https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/fd9460f0bfa9b670d7ef95ba48ec274a5146871c/src/FsToolkit.ErrorHandling/ValueOption.fs#L44

**Comment by T-Gro** [comment]
This is a "witness" method for an F# inline function with statically (compile time) resolved type parameters ("SRTP"s). It is only ever run after type application and inlining.

Is there an extension point by which one can exclude methods from Cecil validation? That could be done as an idea.

**Comment by MichalStrehovsky** [comment]
This is invalid IL, it can crash any of our tools. The tool is not trying to validate things, it parses the assembly according to the file format spec but the assembly is not valid.

**Comment by roboz0r** [comment]
Maybe this is "too much magic" but what if such SRTP constraints were compiled to take advantage of IWSAM?

The offending code 

```fs
let inline tryParse< ^value
    when ^value: (static member TryParse: string * byref< ^value > -> bool)>
    (valueToParse: string)
    : ^value voption =
    let mutable output = Unchecked.defaultof< ^value>

    let parsed =
        (^value: (static member TryParse: string * byref< ^value > -> bool) (valueToParse,
                                                                                &output))

    match parsed with
    | true -> ValueSome output
    | _ -> ValueNone

let f () = 
    let success = tryParse<int> "1234"
    success
```

could be compiled to IL equivalent to

```fs
type ITryParse<'T> =
    static abstract member TryParse: string * byref<'T> -> bool

[<Struct; NoComparison; NoEquality>]
// [<Sealed; AbstractClass>] alternate?
type TryParseInt =
    interface ITryParse<int> with
        static member TryParse(valueToParse: string, output: byref<_>) : bool = System.Int32.TryParse(valueToParse, &output)

let inline tryParse2<'IT, 'T when 'IT :> ITryParse<'T>>
    (valueToParse: string)
    : 'T voption =
    let mutable output = Unchecked.defaultof<'T>

    let parsed = 'IT.TryParse(valueToParse, &output)

    match parsed with
    | true -> ValueSome output
    | _ -> ValueNone
    
let f2 () = 
    let success = tryParse2<TryParseInt, _> "1234"
    success
```

If acceptable I believe this would also solve `FS3532 A trait may not specify optional, in, out, ParamArray, CallerInfo or Quote arguments`

```fs
let inline tryParseOut< ^value
    when ^value: (static member TryParse: string * outref< ^value > -> bool)> // A trait may not specify optional, in, out, ParamArray, CallerInfo or Quote arguments
    (valueToParse: string)
    : ^value voption =
    let mutable output = Unchecked.defaultof< ^value>

    let parsed = (^value: (static member TryParse: string * outref< ^value > -> bool) (valueToParse, &output))

    match parsed with
    | true -> ValueSome output
    | _ -> ValueNone
```

**Comment by T-Gro** [comment]
Interesting idea I have not seem before 👍 .

It could make interop of SRTPs better in the supported scenarios - C# users could decide to implement the consuming interface by hand (whereas F# compiler would know how to emit the interface implementation). I wonder if that is something users regularly want and run into.

IWSAMs are a runtime feature, so the codegen would have to be bound to the targetframework being above a minimal level, ruling out .NET Framework and netstandard.


The only benefit I see is better interop in a (narrow?) use case with C# SRTP consumption.
For this specific bug, I think a more target bugfix of changing the codegen for witnesses to meet the IL spec is a safer and simpler one.

**Comment by roboz0r** [comment]
The reason I came across this was I was experimenting with a way to consume [`Deconstruct` methods](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/deconstruct#user-defined-types) from F# using SRTP. 

I initially thought it was a dead end due to FS3532

```fs
// Doesn't compile
// FS3532 A trait may not specify optional, in, out, ParamArray, CallerInfo or Quote arguments
let inline deconstruct<'T, 'A when 'T: (member Deconstruct : 'A outref -> unit) > (x: 'T) (a: 'A outref) =
    x.Deconstruct(&a)
```

based on the above code I realized `byref` would compile but not `outref`. So I came up with this:

```fs
let inline deconstruct<'T, 'A when 'T: (member Deconstruct : 'A byref -> unit) > (x: 'T) (a: 'A byref) =
    x.Deconstruct(&a)

let inline (|Deconstruct|) x =
    let mutable a = Unchecked.defaultof<_>
    deconstruct x &a
    a

let inline deconstruct2<'T, 'A, 'B when 'T: (member Deconstruct : 'A byref * 'B byref -> unit) > (x: 'T) (a: 'A byref) (b: 'B byref) =
    x.Deconstruct(&a, &b)

let inline (|Deconstruct2|) x =
    let mutable a = Unchecked.defaultof<_>
    let mutable b = Unchecked.defaultof<_>
    deconstruct2 x &a &b
    (a, b)


type X =
    { A: int; B: string }

    member this.Deconstruct(a: int outref) =
        a <- this.A

    member this.Deconstruct(a: int outref, b: string outref) =
        a <- this.A
        b <- this.B


let test () =
    let x = { A = 42; B = "Hello" }
    let (Deconstruct a) = x
    printfn "A: %d" a
    let (Deconstruct2 (a, b)) = x
    printfn "A: %d, B: %s" a b

test ()
```

trying to run this snippet will throw `System.InvalidProgramException`

**Comment by kerams** [comment]
I'd love to see this fixed ASAP. Broken trimming is bad enough for me personally, but it's not hard to imagine a situation where JIT suddenly starts doing some preprocessing that involves reading an entire assembly which would have catastrophic consequences for applications containing F# assemblies (even though SRTPs have exited for years and years, it's not inconcievable that something like this could happen "overnight").

Is there any way the fix could be backwards compatible? Otherwise we could end up in a situation where old compilers will not be able to consume nuget packages compiled with the "fixed" compiler.

**Comment by T-Gro** [comment]
I started to research and the compatibility problems are with quotations - the witnesses exist mainly for those.
If we put quotations out of the picture, we would have multiple fixing paths.

A targeted fix - only change IL codegen for what is certainly known as invalid IL - would be the safest I assume (e.g. just turn `T&` into `T` in the generated IL). The generated IL would not be the same as the F# original, but at the same time we would know that nobody was able to consume it in the past anyway

**Comment by MichalStrehovsky** [comment]
Are these `$W` methods consumed by the F# compiler only? If so, this feels very similar to the `FSharpSignatureData.*`/`FSharpSignatureDataB.*`/`FSharpOptimizationData.*`/`FSharpOptimizationCompressedData.*`/`FSharpOptimizationInfo.*` problem that we discussed recently. The problem in both cases is that the F# compiler places this data into parts of the executable that have meaning to runtime/compilers/trimmers/rewriters/tools.

If the F# compiler were to place this data elsewhere (e.g. embedding a secondary ECMA-335 metadata blob, or even embedding an entire new assembly inside the generated assembly - e.g. into a separate PE section), this section would be ignored by runtime/tools, same as runtime/tools ignore other secondary data in the assembly (e.g. Authenticode digital signatures). It can still be emitted by the same code that is emitting this in the F# compiler and read by the same code, the emission would just happen into a different metadata/code blob. This blob can be invalid from ECMA-335 perspective, because the only thing that would ever interpret it is the F# compiler. IL rewriters would simply drop this data - which is desirable because IL rewriting might require updates to these blobs and the tools don't know how to update it.

E.g. right now, PublishReadyToRun is probably trying to prepare native version of the code in these `$W` methods, bloating the executable (and potentially crashing, depending on how badly malformed the code can get).

**Comment by T-Gro** [comment]
F# compiler does not need those for static compilation, since F# compiler always inlines such F# code even across assembly boundaries (thanks to the resources you mentioned)..

The $W methods are needed in case of quotations, a meta-programming feature that allows to analyze+manipulate+eval stored expression trees at runtime. A subset of it is used e.g. to translate down to expression trees as used by LINQ. And that runtime aspect of it, via library calls, does need the witness $W methods as a `MethodInfo` eventually.

Its somewhat relatable to type-instantiating a generic method at runtime, however with a programming model that is stronger then existing IL generics and therefore needs more data to make it possible to execute dynamically (when used together with the quotations feature)

```fsharp
let inline tryParse< ^value
        when ^value: (static member TryParse: string * byref< ^value > -> bool)>
...
```



The problem is, the authoring code for such a library does not know if eventually any other app will be dynamically evaluating such code with F# quotations or not.
Without that knowledge, we cannot move that information around (since if an app does need it, it will look for a `MethodInfo` eventually. That will fail with this specific `byref` example, I do get that. But the feature works in the general sense)
