### ISSUE TITLE
Find all references hangs forever on any part of active pattern

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#3756]
![1](https://user-images.githubusercontent.com/873919/31587225-a865c7d0-b1e6-11e7-8e39-05f0e137050e.gif)

**Comment by vasily-kirichenko** [comment]
> at Microsoft.CodeAnalysis.Text.TextSpan.FromBounds(Int32 start, Int32 end)
   at Microsoft.CodeAnalysis.Editor.FindUsages.ClassifiedSpansAndHighlightSpanFactory.FillInClassifiedSpanGaps(SourceText sourceText, Int32 startPosition, List`1 classifiedSpans, ArrayBuilder`1 result)
   at Microsoft.CodeAnalysis.Editor.FindUsages.ClassifiedSpansAndHighlightSpanFactory.MergeClassifiedSpans(List`1 syntaxSpans, List`1 semanticSpans, TextSpan widenedSpan, SourceText sourceText)
   at Microsoft.CodeAnalysis.Editor.FindUsages.ClassifiedSpansAndHighlightSpanFactory.<GetClassifiedSpansAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.FindUsages.ClassifiedSpansAndHighlightSpanFactory.<GetTaggedTextForDocumentRegionAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.FindUsages.ClassifiedSpansAndHighlightSpanFactory.<ClassifyAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.FindUsages.ClassifiedSpansAndHighlightSpanFactory.<ClassifyAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.FindUsages.StreamingFindUsagesPresenter.AbstractTableDataSourceFindUsagesContext.<CreateDocumentSpanEntryAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.FindUsages.StreamingFindUsagesPresenter.WithReferencesFindUsagesContext.<AddDeclarationEntriesAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.FindUsages.StreamingFindUsagesPresenter.WithReferencesFindUsagesContext.<OnDefinitionFoundWorkerAsync>d__1.MoveNext()

**Comment by cartermp** [comment]
o_O

What happens if you invoke rename?  Does finding symbols also take forever?  (Not at PC, otherwise I'd try it myself)

**Comment by vasily-kirichenko** [comment]
No, rename works OK.

**Comment by vasily-kirichenko** [comment]
We seem to pass a proper span to Roslyn:

![image](https://user-images.githubusercontent.com/873919/31587524-ed47fda0-b1eb-11e7-951a-8b1cb4d2630a.png)

But it raises the above exception.

@Pilchie any ideas what's wrong with our DefinitionItem?

**Comment by vasily-kirichenko** [comment]
This is what the span looks like on a "good" symbol (i.e. on which Roslyn does not raise exceptions):

![image](https://user-images.githubusercontent.com/873919/31587585-008e0f48-b1ed-11e7-957d-f16e154c1f12.png)

I don't see any difference.

**Comment by Pilchie** [comment]
Looks like the exception is coming from [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/FindUsages/ClassifiedSpansAndHighlightSpanFactory.cs,238).  It's something to do with building up the preview code for the Find All References window.

**Comment by cartermp** [comment]
This doesn't reproduce anymore for me - though there are other issues with active patterns that lead to no results for the repro. But at least the Find References window isn't hung?
