### ISSUE TITLE
Query builder with EF core can't return fsharp tuples (and sometimes new objects) using async methods

### ISSUE THREAD

**Issue by Lanayx** [dotnet/fsharp#3782]
I'm getting an exсeption when using this code

```
    [<CLIMutable>]
    type Product =
        {
            Id: string
            Name: string
        }

    let db = new MyContext()
    let q = query {
        for p in db.Products do
        select (p.Id, p.Name)
    }
    let result = q.ToListAsync().Result
```
If I choose `select p`  or `select p.Id` insead of `select (p.Id, p.Name)` , this works fine. If I write `ToList` instead of `ToListAsync` this works fine as well. C# version with Tuples works well. With provided F# code it fails with this exception:

```
Unhandled Exception: System.InvalidOperationException: The source IQueryable doesn't implement IAsyncEnumerable<System.Tuple`2[System.String,System
.String]>. Only sources that implement IAsyncEnumerable can be used for Entity Framework asynchronous operations.
   at Microsoft.EntityFrameworkCore.Extensions.Internal.QueryableExtensions.AsAsyncEnumerable[TSource](IQueryable`1 source)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToke
n)
```
Also noticed that `select { Id = p.Id; Name = p.Name }` works, while `select { Name = p.Name; Id = p.Id }` doesn't and fails with exception:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (When called from 'VisitLambda', rewriting a node of type 'System.Linq
.Expressions.ParameterExpression' must return a non-null value of the same type. Alternatively, override 'VisitLambda' and change it to not visit c
hildren of this type.) ---> System.InvalidOperationException: When called from 'VisitLambda', rewriting a node of type 'System.Linq.Expressions.Par
ameterExpression' must return a non-null value of the same type. Alternatively, override 'VisitLambda' and change it to not visit children of this
type.
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallE
xpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileAsyncQuery[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvide
r, IDatabase database)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass24_0`1.<CompileAsyncQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQuery[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
```

* Windows 10
* .NET Core 2.0.0
* Microsoft.EntityFrameworkCore 2.0
* FSharp.Core 4.2.3
* FSharp.NET.Sdk 1.0.5

**Comment by ForNeVeR** [comment]
### Notes

1. This works:

    ```fsharp
    let db = new MyContext()
    let q1 = query {
        for p in db.Products do
        select p.Id
    }
    let result = q1.ToListAsync().Result
    ```

    I.e. only the code with tuples won't work.
2. It seems it doesn't work because `q1` (from my sample) has ``Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[System.String]`` type (EF-friendly) while `q` (from @Lanayx sample) has ``System.Linq.EnumerableQuery`1[System.Tuple`2[System.String,System.String]]`` type (non EF-efiendly?).

**Comment by dsyme** [comment]
There is another lingering bug in the treatment of tuples in ``query { ... }`` expressions e.g. #47, I assume this may be related

I assume using an intermediate record type will work.

**Comment by Lanayx** [comment]
There are two bugs here
1) The tuple doesn't work
2) The order of intermediate record fields matters, which shouldn't

**Comment by ForNeVeR** [comment]
@Lanayx could you please provide an example when the order matters? It'll be useful.

**Comment by Lanayx** [comment]
The example is already in the main post right above

**Comment by lucasteles** [comment]
The problem happens with anonymous records too,

```fsharp 
task {
    let db = app.Services.GetRequiredService<AppDbContext>()

    let query1 = // EntityQueryable<<>f__AnonymousType1003022151<string, string>>
        db.Blogs.Select(fun x -> {| Path = x.Slug; Title = x.Name |})

    let query2 = // System.Linq.Enumerable+SelectEnumerableIterator`2[Microsoft.FSharp.Linq.RuntimeHelpers.AnonymousObject`2[System.String,System.String],<>f__AnonymousType1003022151`2[System.String,System.String]]
        query {
            for x in db.Blogs do
                select {| Path = x.Slug; Title = x.Name |}
        }

    let! result1 = query1.ToArrayAsync() // works
    let! result2 = query2.ToArrayAsync() // throws

    return printfn $"%A{result1} | %A{result2}"
}
```

**Comment by xperiandri** [comment]
Any progress on this?

**Comment by lucasteles** [comment]
There is also https://github.com/dotnet/fsharp/issues/15648 which impacts the usage of query builder on EF

**Comment by xperiandri** [comment]
Is this fix intended for F# 10 or F# 11?

**Comment by T-Gro** [comment]
@xperiandri : I want to do a dual insert into NET11 previews BUT ALSO NET 10.0.300  (but not going into the 10.0.10x servicing channel).
