### ISSUE TITLE
Exception: "The path is not of a legal form" when #r argument is invalid

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#4401]
```fsharp
#r " "src\\DotParser\\bin\\Debug\\DotParser.dll"
```

```
One or more errors occurred. The path is not of a legal form.

--- EXCEPTION #1/3 [ArgumentException]
Message = “The path is not of a legal form.”
ExceptionPath.1 = Root.InnerException.InnerException
ExceptionPath.2 = Root.InnerException.InnerExceptions.#0
ClassName = System.ArgumentException
RemoteStackTraceString = “
  at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
     at System.IO.Path.InternalGetDirectoryName(String path)
     at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.Shim.DefaultFileSystem.Microsoft-FSharp-Compiler-AbstractIL-Internal-Library-Shim-IFileSystem-IsInvalidPathShim(String path)
     at Microsoft.FSharp.Compiler.CompileOps.TcConfigBuilder.AddReferencedAssemblyByPath(range m, String path)
     at Microsoft.FSharp.Compiler.CompileOps.ScriptPreprocessClosure.addReferencedAssemblyByPath@5097-3.Invoke(Unit unitVar0, Tuple`2 tupledArg)
     at Microsoft.FSharp.Compiler.CompileOps.ProcessMetaCommand@4858[T](FSharpFunc`2 nowarnF, FSharpFunc`2 loadSourceF, FSharpFunc`2 dllRequireF, TcConfigBuilder tcConfig, String pathOfMetaCommandSource, Boolean canHaveScriptMetaCommands, T state, ParsedHashDirective hash)
”
HResult = E_INVALIDARG=COR_E_ARGUMENT=80070057
Source = FSharp.Compiler.Service
StackTraceString = “
  at Microsoft.FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ReraiseIfWatsonable(Exception exn)
     at Microsoft.FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.ErrorRecovery(ErrorLogger x, Exception exn, range m)
     at Microsoft.FSharp.Compiler.CompileOps.ProcessMetaCommand@4858[T](FSharpFunc`2 nowarnF, FSharpFunc`2 loadSourceF, FSharpFunc`2 dllRequireF, TcConfigBuilder tcConfig, String pathOfMetaCommandSource, Boolean canHaveScriptMetaCommands, T state, ParsedHashDirective hash)
     at Microsoft.FSharp.Compiler.CompileOps.ProcessMetaCommandsFromModuleImpl@4937-1.Invoke(T s, SynModuleDecl d)
     at Microsoft.FSharp.Collections.ListModule.loop@219-29[T,TState](FSharpFunc`3 f, TState s, FSharpList`1 xs)
     at Microsoft.FSharp.Collections.ListModule.loop@219-29[T,TState](FSharpFunc`3 f, TState s, FSharpList`1 xs)
     at Microsoft.FSharp.Compiler.CompileOps.ProcessMetaCommandsFromInput[T](Tuple`3 tupledArg, TcConfigBuilder tcConfig, ParsedInput inp, String pathOfMetaCommandSource, T state0)
     at Microsoft.FSharp.Compiler.CompileOps.ScriptPreprocessClosure.ApplyMetaCommandsFromInputToTcConfigAndGatherNoWarn(TcConfig tcConfig, ParsedInput inp, String pathOfMetaCommandSource)
     at Microsoft.FSharp.Compiler.CompileOps.ScriptPreprocessClosure.loop@5117-90.GenerateNext(IEnumerable`1& next)
     at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
     at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
     at Microsoft.FSharp.Compiler.CompileOps.ScriptPreprocessClosure.loop@5116-89.Invoke(ClosureSource _arg1)
     at Microsoft.FSharp.Compiler.CompileOps.ScriptPreprocessClosure.FindClosureFiles(FSharpList`1 closureSources, TcConfig tcConfig, CodeContext codeContext, LexResourceManager lexResourceManager)
     at Microsoft.FSharp.Compiler.CompileOps.ScriptPreprocessClosure.GetFullClosureOfScriptSource(CompilationThreadToken ctok, Resolver legacyReferenceResolver, String defaultFSharpBinariesDir, String filename, String source, CodeContext codeContext, Boolean useSimpleResolution, Boolean useFsiAuxLib, LexResourceManager lexResourceManager, FSharpFunc`2 applyCommmandLineArgs, Boolean assumeDotNetFramework)
     at Microsoft.FSharp.Compiler.CompileOps.LoadClosure.ComputeClosureOfSourceText(CompilationThreadToken ctok, Resolver legacyReferenceResolver, String defaultFSharpBinariesDir, String filename, String source, CodeContext implicitDefines, Boolean useSimpleResolution, Boolean useFsiAuxLib, LexResourceManager lexResourceManager, FSharpFunc`2 applyCompilerOptions, Boolean assumeDotNetFramework)
     at <StartupCode$FSharp-Compiler-Service>.$Service.GetProjectOptionsFromScript@2776-2.Invoke(ErrorScope _arg30)
     at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CancellableBuilder.Using[c,d](c resource, FSharpFunc`2 e)
     at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CancellableModule.delay@751.Invoke(CancellationToken ct)
     at <StartupCode$FSharp-Compiler-Service>.$Reactor.EnqueueAndAwaitOpAsync@174-2.Invoke(CompilationThreadToken ctok)
”


```

**Comment by charlesroddie** [comment]
It's not Shakespearean but it sounds reasonable.

**Comment by dsyme** [comment]
Going over old FSI bugs. I don't get this error any more:

```
> #r " "src\\DotParser\\bin\\Debug\\DotParser.dll"

  #r " "src\\DotParser\\bin\\Debug\\DotParser.dll"
  ------^^^

stdin(1,7): error FS0010: Unexpected identifier in interaction. Expected incomplete structured construct at or before this point, ';', ';;' or other token.
```
