### ISSUE TITLE
Re-enable disabled VS IDE tests

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#5238]
````
1) Failed : Tests.LanguageService.AutoCompletion.UsingMSBuild.CurriedArguments.Regression1
Couldn't find 'fffff' in completion list: [||]
at Salsa.VsOpsUtils.AssertCompListContains$cont@216(String membername, CompletionItem[] completions, Unit unitVar)
at Salsa.VsOpsUtils.AssertCompListContains(CompletionItem[] completions, String membername)
at Salsa.VsOpsUtils.AssertCompListContainsAll(CompletionItem[] completions, FSharpList`1 expectedCompletions)
at <StartupCode$VisualFSharp-UnitTests>.$Tests.LanguageService.Completion.AssertAutoCompleteContains@59-2.Invoke(CompletionItem[] completions)
at Tests.LanguageService.AutoCompletion.UsingMSBuild.DoWithAutoCompleteUsingExtraRefs(FSharpList`1 refs, Boolean coffeeBreak, SourceFileKind fileKind, BackgroundRequestReason reason, FSharpList`1 code, String marker, FSharpFunc`2 f)
at Tests.LanguageService.AutoCompletion.UsingMSBuild.DoWithAutoComplete(Boolean coffeeBreak, SourceFileKind fileKind, BackgroundRequestReason reason, FSharpList`1 code, String marker, FSharpFunc`2 f)
at <StartupCode$VisualFSharp-UnitTests>.$Tests.LanguageService.Completion.AssertAutoCompleteContains@58-1.Invoke(FSharpList`1 code, String marker, FSharpList`1 should, FSharpList`1 shouldnot)
at Tests.LanguageService.AutoCompletion.UsingMSBuild.CurriedArguments.Regression1()

2) Failed : Tests.LanguageService.AutoCompletion.UsingMSBuild.Identifier.In#Statement
Couldn't find 'Length' in completion list: [||]
at Salsa.VsOpsUtils.AssertCompListContains$cont@216(String membername, CompletionItem[] completions, Unit unitVar)
at Salsa.VsOpsUtils.AssertCompListContains(CompletionItem[] completions, String membername)
at Salsa.VsOpsUtils.AssertCompListContainsAll(CompletionItem[] completions, FSharpList`1 expectedCompletions)

3) Failed : Tests.LanguageService.AutoCompletion.UsingMSBuild.Query.ForKeywordCanCompleteIntoIdentifier
Couldn't find 'form' in completion list: [||]
at Salsa.VsOpsUtils.AssertCompListContains$cont@216(String membername, CompletionItem[] completions, Unit unitVar)
at Salsa.VsOpsUtils.AssertCompListContains(CompletionItem[] completions, String membername)
at Salsa.VsOpsUtils.AssertCompListContainsAll(CompletionItem[] completions, FSharpList`1 expectedCompletions)
at <StartupCode$VisualFSharp-UnitTests>.$Tests.LanguageService.Completion.AssertAutoCompleteContains@59-2.Invoke(CompletionItem[] completions)
at Tests.LanguageService.AutoCompletion.UsingMSBuild.DoWithAutoCompleteUsingExtraRefs(FSharpList`1 refs, Boolean coffeeBreak, SourceFileKind fileKind, BackgroundRequestReason reason, FSharpList`1 code, String marker, FSharpFunc`2 f)
at Tests.LanguageService.AutoCompletion.UsingMSBuild.DoWithAutoComplete(Boolean coffeeBreak, SourceFileKind fileKind, BackgroundRequestReason reason, FSharpList`1 code, String marker, FSharpFunc`2 f)
at <StartupCode$VisualFSharp-UnitTests>.$Tests.LanguageService.Completion.AssertAutoCompleteContains@58-1.Invoke(FSharpList`1 code, String marker, FSharpList`1 should, FSharpList`1 shouldnot)
at Tests.LanguageService.AutoCompletion.UsingMSBuild.Query.ForKeywordCanCompleteIntoIdentifier()

4) Failed : Tests.LanguageService.AutoCompletion.UsingProjectSystem.CurriedArguments.Regression1
Couldn't find 'fffff' in completion list: [||]
at Salsa.VsOpsUtils.AssertCompListContains$cont@216(String membername, CompletionItem[] completions, Unit unitVar)
at Salsa.VsOpsUtils.AssertCompListContains(CompletionItem[] completions, String membername)
at Salsa.VsOpsUtils.AssertCompListContainsAll(CompletionItem[] completions, FSharpList`1 expectedCompletions)
at <StartupCode$VisualFSharp-UnitTests>.$Tests.LanguageService.Completion.AssertAutoCompleteContains@59-2.Invoke(CompletionItem[] completions)
at Tests.LanguageService.AutoCompletion.UsingMSBuild.DoWithAutoCompleteUsingExtraRefs(FSharpList`1 refs, Boolean coffeeBreak, SourceFileKind fileKind, BackgroundRequestReason reason, FSharpList`1 code, String marker, FSharpFunc`2 f)
at Tests.LanguageService.AutoCompletion.UsingMSBuild.DoWithAutoComplete(Boolean coffeeBreak, SourceFileKind fileKind, BackgroundRequestReason reason, FSharpList`1 code, String marker, FSharpFunc`2 f)
at <StartupCode$VisualFSharp-UnitTests>.$Tests.LanguageService.Completion.AssertAutoCompleteContains@58-1.Invoke(FSharpList`1 code, String marker, FSharpList`1 should, FSharpList`1 shouldnot)
at Tests.LanguageService.AutoCompletion.UsingMSBuild.CurriedArguments.Regression1()

5) Failed : Tests.LanguageService.AutoCompletion.UsingProjectSystem.Identifier.In#Statement
Couldn't find 'Length' in completion list: [||]
at Salsa.VsOpsUtils.AssertCompListContains$cont@216(String membername, CompletionItem[] completions, Unit unitVar)
at Salsa.VsOpsUtils.AssertCompListContains(CompletionItem[] completions, String membername)
at Salsa.VsOpsUtils.AssertCompListContainsAll(CompletionItem[] completions, FSharpList`1 expectedCompletions)

6) Failed : Tests.LanguageService.AutoCompletion.UsingProjectSystem.Query.ForKeywordCanCompleteIntoIdentifier
Couldn't find 'form' in completion list: [||]
at Salsa.VsOpsUtils.AssertCompListContains$cont@216(String membername, CompletionItem[] completions, Unit unitVar)
at Salsa.VsOpsUtils.AssertCompListContains(CompletionItem[] completions, String membername)
at Salsa.VsOpsUtils.AssertCompListContainsAll(CompletionItem[] completions, FSharpList`1 expectedCompletions)
at <StartupCode$VisualFSharp-UnitTests>.$Tests.LanguageService.Completion.AssertAutoCompleteContains@59-2.Invoke(CompletionItem[] completions)
at Tests.LanguageService.AutoCompletion.UsingMSBuild.DoWithAutoCompleteUsingExtraRefs(FSharpList`1 refs, Boolean coffeeBreak, SourceFileKind fileKind, BackgroundRequestReason reason, FSharpList`1 code, String marker, FSharpFunc`2 f)
at Tests.LanguageService.AutoCompletion.UsingMSBuild.DoWithAutoComplete(Boolean coffeeBreak, SourceFileKind fileKind, BackgroundRequestReason reason, FSharpList`1 code, String marker, FSharpFunc`2 f)
at <StartupCode$VisualFSharp-UnitTests>.$Tests.LanguageService.Completion.AssertAutoCompleteContains@58-1.Invoke(FSharpList`1 code, String marker, FSharpList`1 should, FSharpList`1 shouldnot)
at Tests.LanguageService.AutoCompletion.UsingMSBuild.Query.ForKeywordCanCompleteIntoIdentifier()

7) Failed : Tests.LanguageService.ParameterInfo.UsingMSBuild.LocationOfParams.TypeProviders.StaticParametersAtConstructorCallSite
  expected parameter info
  Expected: True
  But was:  False
at Tests.LanguageService.ParameterInfo.UsingMSBuild.TestParameterInfoLocationOfParams(String testLine, FSharpOption`1 markAtEOF, FSharpOption`1 additionalReferenceAssemblies)
at Tests.LanguageService.ParameterInfo.UsingMSBuild.TestParameterInfoLocationOfParamsWithVariousSurroundingContexts(String testLine, FSharpOption`1 markAtEnd, FSharpOption`1 additionalReferenceAssemblies)
at Tests.LanguageService.ParameterInfo.UsingMSBuild.LocationOfParams.TypeProviders.StaticParametersAtConstructorCallSite()

8) Failed : Tests.LanguageService.ParameterInfo.UsingProjectSystem.LocationOfParams.TypeProviders.StaticParametersAtConstructorCallSite
  expected parameter info
  Expected: True
  But was:  False
at Tests.LanguageService.ParameterInfo.UsingMSBuild.TestParameterInfoLocationOfParams(String testLine, FSharpOption`1 markAtEOF, FSharpOption`1 additionalReferenceAssemblies)
at Tests.LanguageService.ParameterInfo.UsingMSBuild.TestParameterInfoLocationOfParamsWithVariousSurroundingContexts(String testLine, FSharpOption`1 markAtEnd, FSharpOption`1 additionalReferenceAssemblies)
at Tests.LanguageService.ParameterInfo.UsingMSBuild.LocationOfParams.TypeProviders.StaticParametersAtConstructorCallSite()

````

**Comment by KevinRansom** [comment]
Second Batch:

````
Errors and Failures

1) Error : Tests.LanguageService.Script.UsingMSBuild.Fsx.NoError.HashR.RelativePath1
System.IO.FileNotFoundException : Could not find file 'C:\Users\kevinr\AppData\Local\Temp\salsa-525069609-11648'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at Tests.LanguageService.Script.UsingMSBuild.Fsx.NoError.HashR.RelativePath1()

2) Error : Tests.LanguageService.Script.UsingMSBuild.Fsx.NoError.HashR.RelativePath2
System.IO.FileNotFoundException : Could not find file 'C:\Users\kevinr\AppData\Local\Temp\salsa-525074296-11648'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at Tests.LanguageService.Script.UsingMSBuild.Fsx.NoError.HashR.RelativePath2()

3) Error : Tests.LanguageService.Script.UsingProjectSystem.Fsx.NoError.HashR.RelativePath1
System.IO.FileNotFoundException : Could not find file 'C:\Users\kevinr\AppData\Local\Temp\salsa-525177218-11648'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at Tests.LanguageService.Script.UsingMSBuild.Fsx.NoError.HashR.RelativePath1()

4) Error : Tests.LanguageService.Script.UsingProjectSystem.Fsx.NoError.HashR.RelativePath2
System.IO.FileNotFoundException : Could not find file 'C:\Users\kevinr\AppData\Local\Temp\salsa-525181500-11648'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at Tests.LanguageService.Script.UsingMSBuild.Fsx.NoError.HashR.RelativePath2()

5) Error : Tests.LanguageService.TimeStamp.UsingMSBuild.Regression.NoContainedString.Timestamps.Bug3368a
System.Exception : Error seen containing "project1"
   at Tests.LanguageService.TimeStamp.UsingMSBuild.AssertNoErrorSeenContaining(OpenProject project, String text)
   at Tests.LanguageService.TimeStamp.UsingMSBuild.Regression.NoContainedString.Timestamps.Bug3368a()

6) Failed : Tests.LanguageService.TimeStamp.UsingMSBuild.Timestamps.ProjectReferenceAssemblyChange
  Expected: not equal to 0
  But was:  0
at Tests.LanguageService.TimeStamp.UsingMSBuild.Timestamps.ProjectReferenceAssemblyChange()

7) Failed : Tests.LanguageService.TimeStamp.UsingMSBuild.Timestamps.ReferenceAssemblyChangeAbsolute
  Expected: not equal to 0
  But was:  0
at Tests.LanguageService.TimeStamp.UsingMSBuild.Timestamps.ReferenceAssemblyChangeAbsolute()

8) Failed : Tests.LanguageService.TimeStamp.UsingMSBuild.Timestamps.ReferenceAssemblyChangeRelative
  Expected: not equal to 0
  But was:  0
at Tests.LanguageService.TimeStamp.UsingMSBuild.Timestamps.ReferenceAssemblyChangeRelative()

9) Error : Tests.LanguageService.TimeStamp.UsingProjectSystem.Regression.NoContainedString.Timestamps.Bug3368a
System.Exception : Error seen containing "project1"
   at Tests.LanguageService.TimeStamp.UsingMSBuild.AssertNoErrorSeenContaining(OpenProject project, String text)
   at Tests.LanguageService.TimeStamp.UsingMSBuild.Regression.NoContainedString.Timestamps.Bug3368a()

10) Failed : Tests.LanguageService.TimeStamp.UsingProjectSystem.Timestamps.ProjectReferenceAssemblyChange
  Expected: not equal to 0
  But was:  0
at Tests.LanguageService.TimeStamp.UsingMSBuild.Timestamps.ProjectReferenceAssemblyChange()

11) Failed : Tests.LanguageService.TimeStamp.UsingProjectSystem.Timestamps.ReferenceAssemblyChangeAbsolute
  Expected: not equal to 0
  But was:  0
at Tests.LanguageService.TimeStamp.UsingMSBuild.Timestamps.ReferenceAssemblyChangeAbsolute()

12) Failed : Tests.LanguageService.TimeStamp.UsingProjectSystem.Timestamps.ReferenceAssemblyChangeRelative
  Expected: not equal to 0
  But was:  0
at Tests.LanguageService.TimeStamp.UsingMSBuild.Timestamps.ReferenceAssemblyChangeRelative()

R

````

**Comment by cartermp** [comment]
This should be completed. @KevinRansom please close if this needs to be re-opened.

**Comment by KevinRansom** [comment]
These still need reactivating.
