### ISSUE TITLE
No user code in async stack traces

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#5747]
F# 4.5, FSharp.Core 4.5.2
```
A severe error occurred on the current command.  The results, if any, should be discarded.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at <StartupCode$FSharp-Core>.$Async.callback@1523.Invoke(IAsyncResult iar)
ClientConnectionId:60d2afad-6d79-42eb-9bbf-33a8997abe80
Error Number:916,State:1,Class:14 
```
I cannot determine the code that throws this exception, I mean, *I have absolutely no way to find my code that caused this*.

**Comment by dsyme** [comment]
@vasily-kirichenko Do you have a repro for this please?  Also is it Release of Debug?  The F# 4.5 work was primarily focused on better stack traces for Debug code.

thanks

**Comment by vasily-kirichenko** [comment]
It's Release because it's from production. No, I don't have a repro because I still don't have any clue what code causes this.

**Comment by dsyme** [comment]
Covered by https://github.com/dotnet/fsharp/issues/2741
