### ISSUE TITLE
Fast scrolling in editor crashes VS

### ISSUE THREAD

**Issue by majocha** [dotnet/fsharp#6056]
#### Repro steps

Open a largish .fs file in VS
Scroll quickly using touchbar
VS freezes, then restarts.

#### Known workarounds

Scrolling with the scrollbar does not reproduce this.

#### Related information 
VS 2017 15.9.4
F# release and nightly

This happens with F# files and not C#.
Running PerfView registered this exception:
```
Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FormattedLine'.
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.ThrowIfInvalid()
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.get_Top()
   at Microsoft.VisualStudio.Text.Structure.VisibleBlock.CreateVisibleBlock(IStructureElement structureElement, IWpfTextView view)
   at Microsoft.VisualStudio.Text.Structure.StructureManager.RedrawAdornments(NormalizedSnapshotSpanCollection newOrReformattedSpans)
   at Microsoft.VisualStudio.Text.Structure.StructureManager.<>c__DisplayClass17_0.<OnLayoutChanged>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by cartermp** [comment]
@majocha does this reproduce without the nightly?

**Comment by majocha** [comment]
Just nightly.

**Comment by majocha** [comment]
Happens without nightly, too. It seems hardware specific. I can repro this on one touchpad and not with a mouse.

**Comment by BentTranberg** [comment]
Perhaps specific to hardware in the sense that e.g. different timing affects garbage collection differently. Might be an idea to stresstest this. Put a heavy load on the CPU(s), and see if that can produce an exception when a mouse is used. Also, different mice, or other input devices, could also make a difference.

**Comment by cartermp** [comment]
Thanks @majocha. 

The stack doesn't have any of our code paths on it, but since you only see this with F# perhaps there is something to it. I'm unfamiliar with the namespace, but based on the naming it seems it's Block Structure-related. I'll tag some folks tomorrow (paid holiday today).

**Comment by ricksladkey** [comment]
This is a general problem with Visual Studio unrelated to F#:

* https://developercommunity.visualstudio.com/content/problem/388923/vs-1581-crashes-while-debugging-when-formattedline.html

**Comment by ricksladkey** [comment]
OK, I'm doubting the tags are correct on the bug report I referenced which says C++, and caused me to think that the crash reported in that link was when debugging C++ code.

I am seeing this crash when debugging F# code quite regularly, to the point where it is difficult to complete a debugging session. My Visual Studio Version is 2019 Community 16.1.1 and Microsoft Visual F# Tools 10.4 for F# 4.6.

My call stack is the same but not related to scrolling or the mouse. It occurs during routine debugging (e.g. using F10, F11, etc.) and brings down all of Visual Studio:

```
ObjectDisposedException:

Cannot access a disposed object.
Object name: 'FormattedLine'.

   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.ThrowIfInvalid()
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.get_Top()
   at Microsoft.VisualStudio.Text.Structure.VisibleBlock.CreateVisibleBlock(IStructureElement structureElement, IWpfTextView view)
   at Microsoft.VisualStudio.Text.Structure.StructureManager.RedrawAdornments(NormalizedSnapshotSpanCollection newOrReformattedSpans)
   at Microsoft.VisualStudio.Text.Structure.StructureManager.<>c__DisplayClass17_0.<OnLayoutChanged>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by olegtk** [comment]
@gundermanc ?

**Comment by gundermanc** [comment]
This is a structure guides related stack. You should be able to work around the issue by disabling the feature.

![image](https://user-images.githubusercontent.com/5387680/58646668-bee94f80-82ba-11e9-98f9-3b268b89c893.png)

![image](https://user-images.githubusercontent.com/5387680/58646708-d6c0d380-82ba-11e9-92a6-7c4b48797907.png)

I'll attempt to repro.

**Comment by gundermanc** [comment]
Generally this stack is a sign that the view is closing or in a layout when the TextViewLines collection was accessed but we pretty explicitly check for this, so this must be a more rare situation.

Do any of you have a semi-consistent repro or some tips on how to repro this issue?

**Comment by ricksladkey** [comment]
@gundermanc The view is definitely not closing in my situation. The document window(s) contains F# code and I'm just stepping in or over code with F10 and F11. I've already turned off the structure guides here:

![image](https://user-images.githubusercontent.com/2680524/58651201-a1c67800-82de-11e9-88c7-91add576d8f7.png)

so I probably won't be seeing this crash anymore unless I turn them back on.

**Comment by ricksladkey** [comment]
The symptom is consistent with a formatted line or text view line collection captured from a previous layout being used after another layout has been performed, e.g. by invoking it in the future with the dispatcher.

**Comment by ricksladkey** [comment]
At a bare minimum, the delegate in `StructureManager.<>c__DisplayClass17_0.<OnLayoutChanged>b__0()` needs to be using a try / catch / report with guarded operations so it doesn't crash all of Visual Studio.

**Comment by ricksladkey** [comment]
Checking `ITextViewLine` for `IsClosed` and `InLayout` is only useful prior to retrieving the `TextViewLines` property. Once you have a reference to a text view line collection or text view line (formatted line), it can't possibly be disposed until another layout is done. In any case, checking `ITextViewLine.IsValid` for false will alert the caller that something went horribly wrong because that effectively means the opposite of `IsDisposed`.

**Comment by ricksladkey** [comment]
Lots of other similar bugs, some reported as fixed, and not with F#:

- https://developercommunity.visualstudio.com/content/problem/124319/visual-studio-editor-cannot-access-a-disposed-obje.html
- https://developercommunity.visualstudio.com/content/problem/305243/error-cannot-access-a-disposed-object-object-name-10.html
- https://developercommunity.visualstudio.com/content/problem/106190/when-opening-a-file-to-edit-sometimes-an-error-is.html
- https://developercommunity.visualstudio.com/content/problem/447596/editor-or-extension-exception-report-formattedline.html
- https://developercommunity.visualstudio.com/content/problem/264923/zoom-level-crashes-vs2017-1580-preview-2.html

**Comment by ricksladkey** [comment]
Sorry for so many comments on this thread. Here is, I hope, my last one identifying the exact cause of the bug, which (thankfully?) is not an F# problem.

The method `Microsoft.VisualStudio.Text.Structure.VisibleBlock.CreateVisibleBlock` violates the contract of `GetTextViewLineContainingBufferPosition` method as described in this documentation:

- https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.editor.iwpftextview.gettextviewlinecontainingbufferposition?view=visualstudiosdk-2019

From the Remarks section:

> The returned IWpfTextViewLine **could be invalidated** by either a layout by the view or by **subsequent calls to this method**.

(emphasis added).

In short, any call to `GetTextViewLineContainingBufferPosition` may cause a any existing reference to an `ITextViewLine` to be invalidated, Specifically, this sequence of code is unsafe:

```c#
1)	IWpfTextViewLine firstVisibleLine = view.TextViewLines.FirstVisibleLine;
        ...
2)	ITextViewLine textViewLineContainingBufferPosition = view.GetTextViewLineContainingBufferPosition(guideLineHorizontalAnchorPoint.Value);
        ...
3)	double num = (textViewLineContainingBufferPosition2 == null) ? firstVisibleLine.Top : textViewLineContainingBufferPosition2.Top;
```

Getting the property `Top` at 3) refers to a variable assigned at 1) that **may be invalidated** at 2).

Futhermore, the delegate is invoked directly with `Dispatcher.BeginInvoke` in `Microsoft.VisualStudio.Text.Structure.StructureManager.OnLayoutChanged`, which means any exceptions will bring down all of Visual Studio:

```
		this._view.VisualElement.Dispatcher.BeginInvoke(new Action(delegate
		{
			this.IncrementalRedraw(e.NewOrReformattedSpans);
		}), Array.Empty<object>());
```

**Comment by gundermanc** [comment]
I took a look back when this was originally filed but had to shelve it for a bit when nothing obvious stood out. I've finally been able to circle back to this and investigate more deeply.

> The returned IWpfTextViewLine could be invalidated by either a layout by the view or by subsequent calls to this method.

I took a look at ITextView.GetTextViewLineContainingBufferPosition() and ITextViewLinesCollection.GetTextViewLineContainingBufferPosition() and there no obvious way that calling the IWpfTextView overload can cause an ITextViewLine to get evicted from the ITextViewLinesCollection cache since the two components maintain their own caches. 

Since this is a synchronous, UI thread code path, it _theoretically_ shouldn't be possible to have a layout happen within CreateVisibleBlock().

However, I discussed this at length with a teammate and we've determined that it is possible for a layout or another call to ITextView.GetTextViewLineContainingBufferPosition() to occur if we call into an editor extension that pumps window messages during one of the calls we make to format the line in our call to IWpfTextView.GetTextViewLineContainingBufferPosition().

I haven't found any evidence of such an extension, but perhaps there's a part of F# or a product component that does exactly that. FWIW, some seemingly innocuous code, such as [lock blocks on the UI thread](https://social.msdn.microsoft.com/forums/en-US/ba077ecb-19bc-4a47-9e91-87c99a0c7872/do-threads-calling-lock-ever-do-a-wait-and-pump-messages) apparently pump window messages. This means we're vulnerable to this bug if we happen to call into an ITagger<IClassificationTag> that obtains a lock and the timing is just right.

Just in case, I've applied the suggested change to the Structure Guides code to harden it against this scenario, if an internal F# contact wants to take a look: https://dev.azure.com/devdiv/DevDiv/_git/VS-Platform/pullrequest/256123.

Also, F# seems to have its own from-scratch CodeLens implementation that relies on GetTextViewLineContainingBufferPosition(). I suspect this code is related to why we only see this particular exception stack in F#. Most likely whatever component is doing the message pumping is allowing this code to execute between our calls to `FirstVisibleLine` and `GetTextViewLineContainingBufferPosition()`.

**Comment by realvictorprm** [comment]
@gundermanc that implementation was done by me back then because the code lens API was still internal  + not available for the community edition which forced me to implement something which worked for everyone. However personally I consider the code/line lens to be broken and I didn't find motivation and time for completely refactoring it yet.

**Comment by cartermp** [comment]
@gundermanc thanks for the exhaustive writeup and PR! I'm not familiar with how the editor locks down for a release - will this be slated for 16.7 (some preview) or will this go into 16.8?

Long-term we'll be centralizing on LSP with a CodeLens that comes "for free" and this particular implementation of a CodeLens will go away as a result of that. Are there any gotchas we should be aware of for that?

**Comment by cartermp** [comment]
Thanks, good to know.
