### ISSUE TITLE
Batch remove unused open statements encounters an error

### ISSUE THREAD

**Issue by asik** [dotnet/fsharp#6124]
#### Repro steps

In a file with unused open statements, use the suggested fix "Remove unused open declarations", Project-wide.

#### Expected behavior

Unused open declarations are removed across the project.

#### Actual behavior
![image](https://user-images.githubusercontent.com/1631157/51343900-7052bb80-1a65-11e9-9b10-c7ecaa5a2dfe.png)
```
System.ArgumentNullException : Value cannot be null.
Parameter name: key
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key,TValue value,KeyCollisionBehavior behavior,MutationInput origin)
   at async Microsoft.CodeAnalysis.CodeFixes.FixAllContext.DiagnosticProvider.GetTreeToDocumentMapAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.FixAllContext.DiagnosticProvider.GetDocumentDiagnosticsToFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.FixAllContext.DiagnosticProvider.GetDocumentDiagnosticsToFixWorkerAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.FixAllContext.DiagnosticProvider.GetDocumentDiagnosticsToFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
```

#### Related information 
Visual Studio Enterprise 2017
Version 15.9.5
Visual F# Tools 10.2 for F# 4.5 - 15.8.0.0

**Comment by cartermp** [comment]
Thanks, the stack trace indicates that this isn't directly from F# - though we may be passing bad data to Roslyn causing this.

@jasonmalinowski does this seem like a Roslyn issue?

**Comment by cartermp** [comment]
This was probably fixed upstream in roslyn as the stack trace implicates roslyn. I haven't ever seen this recently, so I'll close this as no repro.
