### ISSUE TITLE
GetProjectOptionsFromScript error in dotnetcore environment

### ISSUE THREAD

**Issue by ronaldschlenker** [dotnet/fsharp#6161]
## Description

When the **FSharpChecker** is used in a selfcontained dotnet core 2.0 application, an error is returned from the **GetProjectOptionsFromScript** function due to a missing 'assembly' folder.

## Reproduce

You can reproduce it in a dotnet core app with this code:

```fsharp
open System
open Microsoft.FSharp.Compiler.SourceCodeServices

[<EntryPoint>]
let main argv =

    let fsx = "test.fsx"
    let source = ""

    let checker = FSharpChecker.Create()
    let options, errors =
        checker.GetProjectOptionsFromScript(fsx, source, DateTime.Now, assumeDotNetFramework=false)
        |> Async.RunSynchronously 
    0
```
*errors* is this:

```
Errors: [startup (1,1)-(1,1) parameter warning System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\ronal\source\repos\FSCError\FSCError\bin\Release\assembly'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.EnumerateDirectories(String path)
   at Microsoft.FSharp.Compiler.SimulatedMSBuildReferenceResolver.options@150.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Microsoft.FSharp.Compiler.SimulatedMSBuildReferenceResolver.SimulatedMSBuildResolver@29.Microsoft-FSharp-Compiler-ReferenceResolver-Resolver-Resolve(ResolutionEnvironment resolutionEnvironment, Tuple`2[] references, String targetFrameworkVersion, FSharpList`1 targetFrameworkDirectories, String targetProcessorArchitecture, String fsharpCoreDir, FSharpList`1 explicitIncludeDirs, String implicitIncludeDir, FSharpFunc`2 logMessage, FSharpFunc`2 logWarningOrError) (Code=SR001)]
```

![image](https://user-images.githubusercontent.com/472222/51936157-d812ea00-2407-11e9-8b6c-421a31ee6b24.png)

## Analysis

https://github.com/Microsoft/visualfsharp/blob/9b55eccd1bc83ed123c5ae08c577be5646861830/src/fsharp/SimulatedMSBuildReferenceResolver.fs#L145-L146

It seems that in these two lines of code, the GAC folder is determined in a 'wrong' way: **System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory()** returns the directory of the application's executable in case of selfcontained dotnet core apps (on Windows), and not the GAC folder (which is of course not necessarily present in selfcontained dotnet core apps).

See also here: https://github.com/georgewfraser/fsharp-language-server/issues/29

**Comment by dsyme** [comment]
I'm going to close this out - my understanding is that GetProjectOptionsFromScript works fine on .NET Core now - at least we use it in many places in our tests

**Comment by cartermp** [comment]
Yes, there are no errors on latest .NET Core and FCS
