### ISSUE TITLE
`dotnet fsi` printing stacktraces on unecognized arguments

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/fsharp#7677]
**Repro steps**

Using dotnet sdk 3.0.100:

```
$ dotnet fsi --foobar

error FS0243: Unrecognized option: '--foobar'

Exception by fsi.exe:
System.Exception: Error creating evaluation session: StopProcessingExn None
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1637.Invoke(String message) in F:\workspace.1\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1637
   at FSharp.Compiler.Interactive.Shell.FsiCommandLineOptions..ctor(FsiEvaluationSessionHostConfig fsi, String[] argv, TcConfigBuilder tcConfigB, FsiConsoleOutput fsiConsoleOutput) in F:\workspace.1\_work\1\s\src\fsharp\fsi\fsi.fs:line 724
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession..ctor(FsiEvaluationSessionHostConfig fsi, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, Boolean fsiCollectible, FSharpOption`1 legacyReferenceResolver) in F:\workspace.1\_work\1\s\src\fsharp\fsi\fsi.fs:line 2446
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.Create(FsiEvaluationSessionHostConfig fsiConfig, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, FSharpOption`1 collectible, FSharpOption`1 legacyReferenceResolver) in F:\workspace.1\_work\1\s\src\fsharp\fsi\fsi.fs:line 2784
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Sample.FSharp.Compiler.Interactive.Main.evaluateSession(String[] argv) in F:\workspace.1\_work\1\s\src\fsharp\fsi\fsimain.fs:line 275
```

#### Expected behavior

Bad cli input should not result in unhandled exceptions.

**Related information**

Happens on Windows & Linux with dotnet sdk v3.0.100

**Comment by cartermp** [comment]
Definitely shouldn't leak the stack trace there

**Comment by ronaldschlenker** [comment]
Also occurs on .Net (not only dotnet fsi).
