### ISSUE TITLE
Getting script options via checker is broken in dotnet fsi

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#7880]
```fsharp
open FSharp.Compiler.SourceCodeServices
open FSharp.Compiler.Text

let ch = FSharpChecker.Create()
let opts, errs =
    ch.GetProjectOptionsFromScript("foo.fsx", SourceText.ofString "")
    |> Async.RunSynchronously
```

```
"C:\Program Files\dotnet\dotnet.exe" fsi --optimize+ --fsi-server:0 --readline- --shadowcopyreferences- --fsi-server-output-codepage:65001 --fsi-server-input-codepage:65001 --fsi-server-lcid:1033

Microsoft (R) F# Interactive version 10.6.0.0 for F# 4.7
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

#r @"C:\Users\Eugene.Auduchinok\Downloads\fsharp.compiler.service.33.0.0\lib\net461\FSharp.Compiler.Service.dll"
open FSharp.Compiler.SourceCodeServices
open FSharp.Compiler.Text
let ch = FSharpChecker.Create()

let opts, errs = ch.GetProjectOptionsFromScript("foo.fsx", SourceText.ofString "") |> Async.RunSynchronously

--> Referenced 'C:\Users\Eugene.Auduchinok\Downloads\fsharp.compiler.service.33.0.0\lib\net461\FSharp.Compiler.Service.dll' (file may be locked by F# Interactive process)

val ch : FSharpChecker
System.TypeInitializationException: The type initializer for '<StartupCode$FSharp-Compiler-Service>.$FSharpCheckerResults' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at <StartupCode$FSharp-Compiler-Service>.$FSharpCheckerResults..cctor()
   --- End of inner exception stack trace ---
   at FSharp.Compiler.SourceCodeServices.FSharpCheckerResultsSettings.get_defaultFSharpBinariesDir()
   at <StartupCode$FSharp-Compiler-Service>.$Service.GetProjectOptionsFromScript@751-2.Invoke(ErrorScope _arg23)
   at FSharp.Compiler.AbstractIL.Internal.Library.CancellableBuilder.Using[c,d](c resource, FSharpFunc`2 e)
   at <StartupCode$FSharp-Compiler-Service>.$Service.GetProjectOptionsFromScript@748-1.Invoke(Unit unitVar)
   at FSharp.Compiler.AbstractIL.Internal.Library.CancellableModule.delay@746.Invoke(CancellationToken ct)
   at <StartupCode$FSharp-Compiler-Service>.$Reactor.EnqueueAndAwaitOpAsync@181-2.Invoke(CompilationThreadToken ctok)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in F:\workspace.1\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 350
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in F:\workspace.1\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 870
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in F:\workspace.1\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 890
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in F:\workspace.1\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1154
   at <StartupCode$FSI_0005>.$FSI_0005.main@()
Stopped due to error
```

Works in .NET Framework fsi:
```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsi.exe" --optimize+ --fsi-server:0 --readline- --shadowcopyreferences- --fsi-server-output-codepage:65001 --fsi-server-input-codepage:65001 --fsi-server-lcid:1033

Microsoft (R) F# Interactive version 10.6.0.0 for F# 4.7
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

#r @"C:\Users\Eugene.Auduchinok\Downloads\fsharp.compiler.service.33.0.0\lib\net461\FSharp.Compiler.Service.dll"
open FSharp.Compiler.SourceCodeServices
open FSharp.Compiler.Text
let ch = FSharpChecker.Create()
let opts, errs = ch.GetProjectOptionsFromScript("foo.fsx", SourceText.ofString "") |> Async.RunSynchronously

--> Referenced 'C:\Users\Eugene.Auduchinok\Downloads\fsharp.compiler.service.33.0.0\lib\net461\FSharp.Compiler.Service.dll' (file may be locked by F# Interactive process)

val ch : FSharp.Compiler.SourceCodeServices.FSharpChecker
val opts : FSharp.Compiler.SourceCodeServices.FSharpProjectOptions =
  { ProjectFileName = "foo.fsx.fsproj"
    ProjectId = None
    SourceFiles = [|"foo.fsx"|]
    OtherOptions =
                  [|"--noframework"; "--warn:3";
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[39 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[37 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[41 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[54 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[75 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[42 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[45 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[42 chars];
                    "-r:C:\Program Files (x86)\Microsoft Visual Studio\2019\Profes"+[68 chars];
                    "-r:C:\Program Files (x86)\Microsoft Visual Studio\2019\Profes"+[93 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[50 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[53 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[50 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[56 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[62 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[61 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[48 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[58 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[57 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[62 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[55 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[41 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[50 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[51 chars];
                    "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Fram"+[46 chars]|]
    ReferencedProjects = [||]
    IsIncompleteTypeCheckEnvironment = false
    UseScriptResolutionRules = true
    LoadTime = 12/31/9999 11:59:59 PM
    UnresolvedReferences = Some UnresolvedReferencesSet []
    OriginalLoadReferences = []
```

**Comment by alfonsogarciacaro** [comment]
Not sure if related, but we're having problems in Fable too with `GetProjectOptionsFromScript` after updating FCS (not the Nuget package, we do a custom build with the latest code from this repo). See https://github.com/fable-compiler/Fable/commit/065da40686933d326780456d5b120d38d8677e91#commitcomment-43397971.

**Comment by dsyme** [comment]
F# Interactive has some issues with FSharp.Compiler.Service, since it is already running a copy of the DLL as part of its implementation. I don't think it's possible to reliably reference anything but exactly that DLL. So this works, for example:
```fsharp
#r "FSharp.Compiler.Service"

open FSharp.Compiler.CodeAnalysis
open FSharp.Compiler.Text

let ch = FSharpChecker.Create()
let opts, errs =
    ch.GetProjectOptionsFromScript("foo.fsx", SourceText.ofString "", assumeDotNetFramework=false)
    |> Async.RunSynchronously
printfn "%A" opts
```
giving
```
E:\GitHub\dsyme\fsharp-compiler-docs\fsharp>dotnet fsi e:\GitHub\dsyme\FSharp.Formatting\a.fsx
{ ProjectFileName = "foo.fsx.fsproj"
  ProjectId = None
  SourceFiles = [|"foo.fsx"|]
  OtherOptions =
   [|"--noframework"; "--warn:3";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\Microsoft.CSharp.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\Microsoft.VisualBasic.Core.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\Microsoft.VisualBasic.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\Microsoft.Win32.Primitives.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\Microsoft.Win32.Registry.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\mscorlib.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\netstandard.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.AppContext.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Buffers.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Collections.Concurrent.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Collections.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Collections.Immutable.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Collections.NonGeneric.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Collections.Specialized.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.ComponentModel.Annotations.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.ComponentModel.DataAnnotations.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.ComponentModel.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.ComponentModel.EventBasedAsync.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.ComponentModel.Primitives.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.ComponentModel.TypeConverter.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Configuration.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Console.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Core.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Data.Common.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Data.DataSetExtensions.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Data.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Diagnostics.Contracts.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Diagnostics.Debug.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Diagnostics.DiagnosticSource.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Diagnostics.FileVersionInfo.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Diagnostics.Process.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Diagnostics.StackTrace.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Diagnostics.TextWriterTraceListener.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Diagnostics.Tools.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Diagnostics.TraceSource.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Diagnostics.Tracing.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Drawing.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Drawing.Primitives.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Dynamic.Runtime.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Formats.Asn1.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Globalization.Calendars.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Globalization.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Globalization.Extensions.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.IO.Compression.Brotli.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.IO.Compression.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.IO.Compression.FileSystem.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.IO.Compression.ZipFile.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.IO.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.IO.FileSystem.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.IO.FileSystem.DriveInfo.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.IO.FileSystem.Primitives.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.IO.FileSystem.Watcher.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.IO.IsolatedStorage.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.IO.MemoryMappedFiles.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.IO.Pipes.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.IO.UnmanagedMemoryStream.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Linq.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Linq.Expressions.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Linq.Parallel.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Linq.Queryable.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Memory.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.Http.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.Http.Json.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.HttpListener.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.Mail.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.NameResolution.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.NetworkInformation.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.Ping.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.Primitives.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.Requests.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.Security.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.ServicePoint.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.Sockets.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.WebClient.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.WebHeaderCollection.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.WebProxy.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.WebSockets.Client.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Net.WebSockets.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Numerics.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Numerics.Vectors.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.ObjectModel.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Reflection.DispatchProxy.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Reflection.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Reflection.Emit.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Reflection.Emit.ILGeneration.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Reflection.Emit.Lightweight.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Reflection.Extensions.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Reflection.Metadata.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Reflection.Primitives.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Reflection.TypeExtensions.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Resources.Reader.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Resources.ResourceManager.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Resources.Writer.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Runtime.CompilerServices.Unsafe.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Runtime.CompilerServices.VisualC.dll";
     "-r:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.2.21480.5\ref\net6.0\System.Runtime.dll";
     ...|]
  ReferencedProjects = [||]
  IsIncompleteTypeCheckEnvironment = false
  UseScriptResolutionRules = true
  LoadTime = 31/12/9999 23:59:59
  UnresolvedReferences = Some FSharpUnresolvedReferencesSet []
  OriginalLoadReferences = []
  Stamp = None }

E:\GitHub\dsyme\fsharp-compiler-docs\fsharp>
```
