### ISSUE TITLE
Exception raised during pretty printing

### ISSUE THREAD

**Issue by jimfoye** [dotnet/fsharp#8003]
Start new instance of FSI in Visual Studio 2019. Output:

Microsoft (R) F# Interactive version 10.7.0.0 for F# 4.7

Send this to FSI:

System.IntPtr.Zero.ToPointer()

Result:

Exception raised during pretty printing.
Please report this so it can be fixed.
Trace: System.ArgumentException: The type 'System.Void*' may not be used as a type argument.
   at System.RuntimeType.ThrowIfTypeNeverValidGenericArgument(RuntimeType type)
   at System.RuntimeType.SanityCheckGenericArguments(RuntimeType[] genericArguments, RuntimeType[] genericParamters)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at FSharp.Compiler.Interactive.Shell.Utilities.getAnyToLayoutCall(Type ty) in F:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 82
   at FSharp.Compiler.Interactive.Shell.FsiValuePrinter.PrintValue(FsiValuePrinterMode printMode, FormatOptions opts, Object x, Type ty) in F:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 384
val it : voidptr = 

>

**Comment by dsyme** [comment]
In `getAnyToLayoutCall` we should ignore any pointer type being passed down as the System.Type

**Comment by abonie** [comment]
So... what expected behavior here, anything sensible to print on the right hand side, or can it be just skipped like so:
```
> System.IntPtr.Zero.ToPointer();;
val it: voidptr
```
