### ISSUE TITLE
off by one error in reported lines in stacktraces

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#8071]
Reported lines in F# stack traces have off by one error while C# and VB.NET behaves normally.

attached reproduce cases:
[stacktraces.zip](https://github.com/dotnet/fsharp/files/4014918/stacktraces.zip)

```csharp
using System;

namespace csharp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            throw new Exception("fail"); // line 10
        }
    }
}
```

```fsharp
// Learn more about F# at http://fsharp.org

open System

[<EntryPoint>]
let main argv =
    printfn "Hello World from F#!"
    raise (new Exception("fail")) // line 8
    0 // return an integer exit code
```

```vb.net
Imports System

Module Program
    Sub Main(args As String())
        Console.WriteLine("Hello World!")
        Throw New Exception("fail") // line 6
    End Sub
End Module
```

```
C:\tmp\stacktraces\csharp>dotnet run
Hello World!
Unhandled exception. System.Exception: fail
at csharp.Program.Main(String[] args) in C:\tmp\stacktraces\csharp\Program.cs:line 10
C:\tmp\stacktraces\csharp>cd ..
C:\tmp\stacktraces>cd fsharp
C:\tmp\stacktraces\fsharp>dotnet run
Hello World from F#!
Unhandled exception. System.Exception: fail
at Program.main(String[] argv) in C:\tmp\stacktraces\fsharp\Program.fs:line 9
C:\tmp\stacktraces\fsharp>cd ..
C:\tmp\stacktraces>cd vbsharp
C:\tmp\stacktraces\vbsharp>dotnet run
Hello World!
Unhandled exception. System.Exception: fail
at vbsharp.Program.Main(String[] args) in C:\tmp\stacktraces\vbsharp\Program.vb:line 6
```

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by cartermp** [comment]
Wow, I'm surprised this hasn't been reported before. Or perhaps it's a regression?

Note that the correct line is reported for exceptions that aren't raised in user code:

```fsharp
// Learn more about F# at http://fsharp.org

open System

let f () =
    raise (new Exception("fail")) // line 6
    failwith "fail" // line 7

let g () =
    [||].[0] // Line 10

[<EntryPoint>]
let main argv =
    printfn "Hello World from F#!"
    g() // Line 15
    0 // return an integer exit code
```

Stack trace:
```
λ ~/scratch/test-sa/ dotnet run
Hello World from F#!
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Program.g[a]() in /Users/phillip/scratch/test-sa/Program.fs:line 10
   at Program.main(String[] argv) in /Users/phillip/scratch/test-sa/Program.fs:line 15
```

**Comment by dsyme** [comment]
I checked and this has been fixed by recent debugging improvements
