### ISSUE TITLE
Some type initialization exceptions can't be caught.

### ISSUE THREAD

**Issue by goswinr** [dotnet/fsharp#8639]
Some type initialization exceptions can't be caught.
Or are caught, but still print to the error stream.
Evaluation seems to continue.

see [tweets](https://twitter.com/jonharrop/status/1233197575320326144) by @jdh30 

sending these lines to FSI (via FCS 33.0.1 on net472) :

``` fsharp
let mutable globalException : System.Exception = null 

let myGlobal =
  if isNull globalException then                      
    try                                               
      System.IO.File.ReadAllText "DoesNotExist.txt"
    with e ->                                         
      globalException <- e                            
      Unchecked.defaultof<_>                          
  else Unchecked.defaultof<_>                         

```
prints this error, despite enclosure in  the `try .. with e -> ..` .

```fsharp
val mutable globalException : System.Exception =
  System.IO.FileNotFoundException: Could not find file 'D:\Git\Seff\bin\Debug\net472\DoesNotExist.txt'.
File name: 'D:\Git\Seff\bin\Debug\net472\DoesNotExist.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at <StartupCode$FSI_0001>.$FSI_0001.main@() in D:\Git\Seff\bin\Debug\net472\input.fsx:line 7
val myGlobal : string = null
```

Oddly, sending first 
```fsharp
let mutable globalException : System.Exception = null 
```
and then the  block 
```fsharp
let myGlobal = 
    ...
    ...
```
to fsi does not print any error.

**Comment by dsyme** [comment]
The exception is being caught - what you are seeing is the printing of he exception as a value.
