### ISSUE TITLE
Missing method exception on .NET 5 preview

### ISSUE THREAD

**Issue by kerams** [dotnet/fsharp#8743]
I've encountered a runtime error in a simple console application using FSharp.Data. The error message is the same as in https://github.com/fsharp/FSharp.Data/issues/605

**Repro steps**

- Install the `5.0.100-preview.1.20155.7` SDK.
- `dotnet run` a `netcoreapp3.1` project that uses the `Load` method of the HTML type provider (I assume this is all it takes - if not, I can provide a better repro)

**Expected behavior**

No exception.

**Actual behavior**

```
Unhandled exception. System.MissingMethodException: Method not found: 'Microsoft.FSharp.Control.FSharpAsync`1<System.IO.TextReader> FSharp.Data.Runtime.IO.asyncReadTextAtRuntime(System.Boolean, System.String, System.String, System.String, System.String, System.String)'
``` 

**Known workarounds**

Use an older SDK version with global.json:

```
{
  "sdk": {
    "version": "3.1.100"
  }
}
```

However, this does not help with progams built from within VS 16.6 Preview 1 as they fail at runtime regardless.

**Related information**

Provide any related information (optional):

* Windows 10
* SDK: 5.0.100-preview.1.20155.7 and 3.1.101
* VS 16.6 Preview 1

**Comment by cartermp** [comment]
This doesn't require targeting .NET Core 3.1.x, so there's an issue here specifically with .NET 5:

1. Get the .NET 5 SDK (latest preview)
2. `dotnet new console -lang F# -o fsdatatest`
3. `cd fsdatatest && dotnet add package fsharp.data`
4.

```fsharp
// Learn more about F# at http://fsharp.org

open System
open FSharp.Data

[<Literal>]
let url =  @"https://en.wikipedia.org/wiki/2017_FIA_Formula_One_World_Championship"

type F1_2017 = HtmlProvider<url>

// Download the latest market depth information
let f1Calendar = 
    F1_2017.Load(url).Tables.``Season calendar``

[<EntryPoint>]
let main argv =
    for row in f1Calendar.Rows do
        printfn "%A" row.``Grand Prix``
    0 // return an integer exit code
```

5. `dotnet run`

```
λ ~/scratch/fsdatatest/ dotnet run
Unhandled exception. System.TypeInitializationException: The type initializer for 'Program' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<StartupCode$fsdatatest>.$Program' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Microsoft.FSharp.Control.FSharpAsync`1<System.IO.TextReader> FSharp.Data.Runtime.IO.asyncReadTextAtRuntime(System.Boolean, System.String, System.String, System.String, System.String, System.String)'.
   --- End of inner exception stack trace ---
   at Program..cctor()
   --- End of inner exception stack trace ---
   at Program.main(String[] argv) in /Users/phillip/scratch/fsdatatest/Program.fs:line 17
```

**Comment by cartermp** [comment]
Also linking https://github.com/dotnet/fsharp/issues/8881 https://github.com/dotnet/fsharp/issues/8913
