### ISSUE TITLE
Nullref in FSI with bogus inheritance from generic class

### ISSUE THREAD

**Issue by latkin** [dotnet/fsharp#936]
Related to https://github.com/Microsoft/visualfsharp/issues/935

``` fsharp
type A<'t>(x : 't) = class end

type B<'t> = class inherit A<'t> end
```

FSC compiles this without error or warning (per linked issue, maybe it _should_ have an error).

Evaluating in FSI causes internal error -

```
error FS0193: internal error: Object reference not set to an instance of an object.
Stack Trace
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Reflection.Emit.TypeBuilder.GetConstructor(Type type, ConstructorInfo constructor)
   at System.Reflection.Emit.TypeBuilder.DefineDefaultConstructorNoLock(MethodAttributes attributes)
   at System.Reflection.Emit.TypeBuilder.DefineDefaultConstructor(MethodAttributes attributes)
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateType()
   at Microsoft.FSharp.Compiler.AbstractIL.ILRuntimeWriter.TypeBuilder.CreateTypeAndLog(TypeBuilder ) in C:\src\visualfsharp\src\absil\ilreflect.fs:line 150
   at Microsoft.FSharp.Compiler.AbstractIL.ILRuntimeWriter.traverseTypeRef@1863.Invoke(Int32 priority, ILTypeRef tref) in C:\src\visualfsharp\src\absil\ilreflect.fs:line 1890
   at Microsoft.FSharp.Compiler.AbstractIL.ILRuntimeWriter.createTypeRef(Dictionary`2 visited, Dictionary`2 created, emEnv emEnv, ILTypeRef tref) in C:\src\visualfsharp\src\absil\ilreflect.fs:line 1820
   at Microsoft.FSharp.Compiler.AbstractIL.ILRuntimeWriter.buildTypeDefPass4(Dictionary`2 visited, Dictionary`2 created, FSharpList`1 nesting, emEnv emEnv, ILTypeDef tdef) in C:\src\visualfsharp\src\absil\ilreflect.fs:line 1897
   at Microsoft.FSharp.Compiler.AbstractIL.ILRuntimeWriter.buildTypeDefPass4@1902.Invoke(ILTypeDef tdef) in C:\src\visualfsharp\src\absil\ilreflect.fs:line 1902
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in C:\src\visualfsharp\src\fsharp\FSharp.Core\seq.fs:line 910
   at Microsoft.FSharp.Compiler.AbstractIL.ILRuntimeWriter.buildModuleFragment@1935-1.Invoke(ILTypeDef tdef) in C:\src\visualfsharp\src\absil\ilreflect.fs:line 1935
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x) in C:\src\visualfsharp\src\fsharp\FSharp.Core\local.fs:line 25
   at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list) in C:\src\visualfsharp\src\fsharp\FSharp.Core\list.fs:line 106
   at Microsoft.FSharp.Compiler.AbstractIL.ILRuntimeWriter.buildModuleFragment(cenv cenv, emEnv emEnv, AssemblyBuilder asmB, ModuleBuilder modB, ILModuleDef m) in C:\src\visualfsharp\src\absil\ilreflect.fs:line 1935
   at Microsoft.FSharp.Compiler.AbstractIL.ILRuntimeWriter.emitModuleFragment(ILGlobals ilg, emEnv emEnv, AssemblyBuilder asmB, ModuleBuilder modB, ILModuleDef modul, Boolean debugInfo, FSharpFunc`2 resolvePath) in C:\src\visualfsharp\src\absil\ilreflect.fs:line 1973
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompiler.ProcessInputs(FsiDynamicCompilerState istate, FSharpList`1 inputs, Boolean showTypes, Boolean isIncrementalFragment, Boolean isInteractiveItExpr, FSharpList`1 prefixPath) in C:\src\visualfsharp\src\fsharp\fsi\fsi.fs:line 862
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompiler.EvalParsedDefinitions(FsiDynamicCompilerState istate, Boolean showTypes, Boolean isInteractiveItExpr, FSharpList`1 defs) in C:\src\visualfsharp\src\fsharp\fsi\fsi.fs:line 950
   at Microsoft.FSharp.Compiler.Interactive.Shell.clo@1591-46.Invoke(FsiDynamicCompilerState istate) in C:\src\visualfsharp\src\fsharp\fsi\fsi.fs:line 1598
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.InteractiveCatch[a](FSharpFunc`2 f, a istate) in C:\src\visualfsharp\src\fsharp\fsi\fsi.fs:line 1545
```

**Comment by dsyme** [comment]
Thanks, definitely a bug, we're probably calling DefineDefaultConstructor on an instantiation.  Or it's a bug in RefEmit (less likely)

**Comment by dsyme** [comment]
Fixed by `--multiemit+` which is on by default for .NET Core
