### ISSUE TITLE
Skipping: FSharp.Compiler.UnitTests (could not find dependent assembly 'FSharp.Compiler.UnitTests, Version=11.0.0') No test matches the given testcase filter `TestCategory!=PullRequest` in C:\kevinransom\fsharp\artifacts\bin\FSharp.Compiler.UnitTests\release\net472\FSharp.Compiler.UnitTests.dll

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#9899]
I just ran 
````
build -c release -testcompiler
````
Wnen I looked at the output I noticed this:

````
Test run for C:\kevinransom\fsharp\artifacts\bin\FSharp.Compiler.UnitTests\release\net472\FSharp.Compiler.UnitTests.dll(.NETFramework,Version=v4.7.2)
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
NUnit Adapter 3.11.2.0: Test execution started
Running all tests in C:\kevinransom\fsharp\artifacts\bin\FSharp.Compiler.UnitTests\release\net472\FSharp.Compiler.UnitTests.dll
   NUnit couldn't find any tests in C:\kevinransom\fsharp\artifacts\bin\FSharp.Compiler.UnitTests\release\net472\FSharp.Compiler.UnitTests.dll
NUnit Adapter 3.11.2.0: Test execution complete
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.1 (32-bit Desktop .NET 4.0.30319.42000)
[xUnit.net 00:00:04.31] Skipping: FSharp.Compiler.UnitTests (could not find dependent assembly 'FSharp.Compiler.UnitTests, Version=11.0.0')
No test matches the given testcase filter `TestCategory!=PullRequest` in C:\kevinransom\fsharp\artifacts\bin\FSharp.Compiler.UnitTests\release\net472\FSharp.Compiler.UnitTests.dll
Results File: C:\kevinransom\fsharp\artifacts\TestResults\release\FSharp.Compiler.UnitTests_net472.xml
````

I doubt this is doing the right thing.

**Comment by abelbraaksma** [comment]
This is weird. I do get:
![image](https://user-images.githubusercontent.com/16015770/89690415-bb157c00-d906-11ea-81eb-57f5b91d0da9.png)

And then:
![image](https://user-images.githubusercontent.com/16015770/89690440-c9fc2e80-d906-11ea-8072-c972cc3939bf.png)

And then later:
![image](https://user-images.githubusercontent.com/16015770/89690496-ef893800-d906-11ea-9385-aa42032ed4d4.png)

But I always run the tests with added `-ci -bl`, as otherwise I keep getting very, very weird errors. So in this case I used:

```
build -testCompiler -ci -bl -c Release
```

**Comment by KevinRansom** [comment]
It's probably an installed netsdk thing.

**Comment by abelbraaksma** [comment]
Hmm, comparing our outputs, you have:

```
Running all tests in C:\kevinransom\fsharp\artifacts\bin\FSharp.Compiler.UnitTests\release\net472\FSharp.Compiler.UnitTests.dll
   NUnit couldn't find any tests in C:\kevinransom\fsharp\artifacts\bin\FSharp.Compiler.UnitTests\release\net472\FSharp.Compiler.UnitTests.dll
```

And on that same DLL NUnit finds a bunch of tests for me. Wonder if the difference is the `-ci` setting?

**Comment by abelbraaksma** [comment]
> Wonder if the difference is the -ci setting?

Nope, I'm just running it without that param and this appears the only testset that actually works without crashing or weird errors and without `-ci`. 

> It's probably an installed netsdk thing.

The log in your post is odd that NUnit cannot find anything in the assembly... You may try run the assembly using the NUnit gui runner, see if that works on your machine?

**Comment by vzarytovskii** [comment]
There's same issue in the Compiler.ComponentTests as well. XUnit runner cannot discover anything in net472 assembly. That is also a reason why only netcoreapp3.1 tests are shown in the test explorer.

I'm looking into it.

**Comment by abelbraaksma** [comment]
@vzarytovskii, it's not just xUnit, it's NUnit too. There should be 185 tests, but none is found on @KevinRansom's machine. On my machine, NUnit works, not sure there are xUnit tests in that assembly (if there are, and they give issues like you say, we can simply turn them into nunit tests for the time being?)

**Comment by vzarytovskii** [comment]
@abelbraaksma What puzzles me is that discovery works just fine with netcoreapp3.1 assembly, but not with net472.

**Comment by vzarytovskii** [comment]
After some testhost and xunit adapter debugging, it appears, that it has something to do with test assembly loading (or the way how xunit does it).
```
BulkDeserializer	{
System.IO.FileLoadException: Could not load file or assembly 'FSharp.Compiler.ComponentTests, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
File name: 'FSharp.Compiler.ComponentTests, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Xunit.Sdk.ReflectionAssemblyInfo..ctor(String assemblyFileName) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionAssemblyInfo.cs:line 33   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ExceptionExtensions.RethrowWithNoStackTraceLoss(Exception ex) in C:\Dev\xunit\xunit\src\common\ExceptionExtensions.cs:line 27
   at Xunit.AppDomainManager_AppDomain.CreateObject[TObject](AssemblyName assemblyName, String typeName, Object[] args) in C:\Dev\xunit\xunit\src\xunit.runner.utility\AppDomain\AppDomainManager_AppDomain.cs:line 84
   at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2Discoverer.cs:line 102
   at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2Discoverer.cs:line 62
   at Xunit.Xunit2..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyTestAssemblyExists) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2.cs:line 41
   at Xunit.XunitFrontController.CreateInnerController() in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 136
   at Xunit.XunitFrontController.EnsureInitialized() in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 163
   at Xunit.XunitFrontController.get_BulkDeserializer() in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 81

=== Pre-bind state information ===
LOG: Where-ref bind. Location = C:/Users/vlza/source/repos/fsharp/artifacts/bin/FSharp.Compiler.ComponentTests/Debug/net472/FSharp.Compiler.ComponentTests.dll
LOG: Appbase = file:///C:/Users/vlza/source/repos/fsharp/artifacts/bin/FSharp.Compiler.ComponentTests/Debug/net472
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Users\vlza\source\repos\fsharp\artifacts\bin\FSharp.Compiler.ComponentTests\Debug\net472\FSharp.Compiler.ComponentTests.dll.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Attempting download of new URL file:///C:/Users/vlza/source/repos/fsharp/artifacts/bin/FSharp.Compiler.ComponentTests/Debug/net472/FSharp.Compiler.ComponentTests.dll.
LOG: Post-policy reference: FSharp.Compiler.ComponentTests, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Using application configuration file: C:\Users\vlza\source\repos\fsharp\artifacts\bin\FSharp.Compiler.ComponentTests\Debug\net472\FSharp.Compiler.ComponentTests.dll.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: FSharp.Compiler.ComponentTests, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/Users/vlza/source/repos/fsharp/artifacts/bin/FSharp.Compiler.ComponentTests/Debug/net472/FSharp.Compiler.ComponentTests.DLL.
ERR: Failed to complete setup of assembly (hr = 0x80131045). Probing terminated.
}	Xunit.ITestCaseBulkDeserializer {System.IO.FileLoadException}

```
namely, signature checking:
```
Could not load file or assembly 'FSharp.Compiler.ComponentTests, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 
Strong name signature could not be verified.  
The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. 
(Exception from HRESULT: 0x80131045)
```

Going to look into it more.

**Comment by vzarytovskii** [comment]
Quick googling showed, that many projects, which are using xunit, have similar problems.
Here's the issues from vstest: https://github.com/microsoft/vstest/issues/1684

**Comment by vzarytovskii** [comment]
Console run should be addressed here: #9909 
I am still investigating why netfx tests do not show in the tests explorer. It seems like the same issue with Assembly loader in the xUnit.

**Comment by abelbraaksma** [comment]
> Strong name signature could not be verified.  

What signature is used for local run, if any? 

Cause this sounds a lot like the dll loading issue in VS when trying to run FSI from running Visualfsharp.sln in a new IDE: that shows a similar error. 

Which suggests that there's something amiss with the signing?
