### ISSUE TITLE
TMI when passing an invalid commandline option to FSI.exe

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#9986]
We show a full stacktrace whenever you pass a wrong commandline option. That isn't very neat, I think we ought to just print the error instead.

This is current:

```
error FS0243: Unrecognized option: '--version'

Exception by fsi.exe:
System.Exception: Error creating evaluation session: StopProcessingExn None
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1639.Invoke(String message)
   at FSharp.Compiler.Interactive.Shell.FsiCommandLineOptions..ctor(FsiEvaluationSessionHostConfig fsi, String[] argv, TcConfigBuilder tcConfigB, FsiConsoleOutput fsiConsoleOutput)
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession..ctor(FsiEvaluationSessionHostConfig fsi, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, Boolean fsiCollectible, FSharpOption`1 legacyReferenceResolver)
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.Create(FsiEvaluationSessionHostConfig fsiConfig, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, FSharpOption`1 collectible, FSharpOption`1 legacyReferenceResolver)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Sample.FSharp.Compiler.Interactive.Main.evaluateSession(String[] argv)
```

Expected:

```
error FS0243: Unrecognized option: '--version'
```

Or even better, we can dump the `--help` screen whenever an invalid commandline is passed, or a simple line saying "use --help for help".

**Comment by abelbraaksma** [comment]
@vzarytovskii, you moved this to `Not planned`, but it has meanwhile been fixed. I'll adjust status accordingly.

**Comment by vzarytovskii** [comment]
Sure, but please don't add or change any impact labels, those are for internal use only.
